import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const developmentPreviewMeta=/<meta(?=[^>]*\bname=["']codex-preview["'])(?=[^>]*\bcontent=["']development["'])[^>]*>/i;
test("renders development preview metadata",async()=>{const workerUrl=new URL("../dist/server/index.js",import.meta.url);workerUrl.searchParams.set("test",`${process.pid}-${Date.now()}`);const{default:worker}=await import(workerUrl.href);const response=await worker.fetch(new Request("http://localhost/",{headers:{accept:"text/html"}}),{ASSETS:{fetch:async()=>new Response("Not found",{status:404})}},{waitUntil(){},passThroughOnException(){}});assert.equal(response.status,200);assert.match(response.headers.get("content-type")??"",/^text\/html\b/i);assert.match(await response.text(),developmentPreviewMeta)});
test("official Konsens logo and pedagogical promise are used by web identity",async()=>{const shell=await readFile(new URL("../app/finance-shell.tsx",import.meta.url),"utf8");const layout=await readFile(new URL("../app/layout.tsx",import.meta.url),"utf8");assert.match(shell,/konsens-logo\.png/);assert.match(shell,/ENTRAÎNE TON INTELLIGENCE FINANCIÈRE/);assert.match(shell,/Aujourd’hui/);assert.doesNotMatch(shell,/f-mark[^\n]*<b>K<\/b>/);assert.match(layout,/Entraîne ton intelligence financière/)});
test("V3 replaces dashboard home with a daily four-step journey",async()=>{const source=await readFile(new URL("../app/today-v3.tsx",import.meta.url),"utf8");assert.match(source,/get_my_daily_journey/);assert.match(source,/get_my_konsens_score/);assert.match(source,/refresh_my_coach_insights/);assert.match(source,/COMPRENDRE|comprendre/);assert.match(source,/PRÉDIRE|predict/);assert.match(source,/DÉCIDER|decide/);assert.match(source,/APPRENDRE|learn/);assert.match(source,/Chaque jour, entraîne ta capacité à prendre de meilleures décisions avec l’argent/);assert.match(source,/Replay/);assert.match(source,/get_discoverable_leagues/);assert.match(source,/Partager ma carte/)});
test("decision journal asks reason and confidence after simulated trades",async()=>{const source=await readFile(new URL("../app/decision-reflection.tsx",import.meta.url),"utf8");assert.match(source,/decision_journal/);assert.match(source,/konsens:trade/);assert.match(source,/reason_code/);assert.match(source,/confidence/);assert.match(source,/reviewed_at/);assert.match(source,/Pourquoi as-tu pris cette décision/)});
test("consensus is a central comparison object",async()=>{const source=await readFile(new URL("../app/consensus-v3.tsx",import.meta.url),"utf8");assert.match(source,/get_market_consensus_comparison/);assert.match(source,/COMMUNAUTÉ/);assert.match(source,/POINT DE DÉPART/);assert.match(source,/TOI/)});
test("what-if lab uses captured market history and premium persistence",async()=>{const source=await readFile(new URL("../app/what-if-v3.tsx",import.meta.url),"utf8");assert.match(source,/simulate_asset_what_if/);assert.match(source,/saved_scenarios/);assert.match(source,/history_limited/);assert.match(source,/ne prédit pas le futur/)});
test("Play quick OUI NON keeps the real Koin ticket",async()=>{const source=await readFile(new URL("../app/prediction-v2.tsx",import.meta.url),"utf8");assert.match(source,/from\("trade_orders"\)\.insert/);assert.match(source,/onQuick=\{o=>openTicket\(m,o\)\}/);assert.match(source,/id="play-ticket"/);assert.match(source,/Confirmer \$\{pendingOutcome\.toUpperCase\(\)\}/);assert.match(source,/trade\("sell","yes"\)/);assert.match(source,/market_watchlist/)});
test("Finance keeps real reference data portfolio fundamentals and persistent news",async()=>{const source=await readFile(new URL("../app/live-finance-v2.tsx",import.meta.url),"utf8");assert.match(source,/functions\/v1\/market-data/);assert.match(source,/functions\/v1\/finance-news/);assert.match(source,/fundamentals/);assert.match(source,/Suivre mes investissements/);assert.match(source,/asset_watchlist/);assert.match(source,/trade\("buy"\)/);assert.match(source,/trade\("sell"\)/);assert.match(source,/newsByAsset/);assert.match(source,/articles\.length>0/);assert.match(source,/newsRequest/);assert.doesNotMatch(source,/setNews\(\[\]\)/)});
test("Academy persists real quiz progress",async()=>{const source=await readFile(new URL("../app/academy-v2.tsx",import.meta.url),"utf8");assert.match(source,/from\("learning_progress"\)\.upsert/);assert.match(source,/Valider le module/)});
test("Premium V3 sells advanced Coach and Portfolio Lab while retaining beta entitlement",async()=>{const source=await readFile(new URL("../app/premium-v2.tsx",import.meta.url),"utf8");assert.match(source,/start_premium_beta_trial/);assert.match(source,/Coach avancé/);assert.match(source,/Portfolio Lab/);assert.match(source,/Whale Watch/);assert.match(source,/Activer 14 jours gratuitement/)});
test("notification center subscribes to user alerts and registers service worker",async()=>{const source=await readFile(new URL("../app/notification-center.tsx",import.meta.url),"utf8");assert.match(source,/notification_events/);assert.match(source,/postgres_changes/);assert.match(source,/serviceWorker\.register\("\/sw\.js"\)/);assert.match(source,/Notification\.requestPermission/)});
test("blockchain transparency keeps public leaderboard and Premium alerts",async()=>{const source=await readFile(new URL("../app/blockchain-v2.tsx",import.meta.url),"utf8");assert.match(source,/get_whale_leaderboard/);assert.match(source,/set_wallet_alert/);assert.match(source,/functions\/v1\/blockchain-data/);assert.match(source,/Premium/)});
test("monetization remains connected after pedagogical pivot",async()=>{const revenue=await readFile(new URL("../app/monetization/page.tsx",import.meta.url),"utf8");const ads=await readFile(new URL("../app/monetization/ads/page.tsx",import.meta.url),"utf8");const providers=await readFile(new URL("../app/monetization/providers/page.tsx",import.meta.url),"utf8");assert.match(revenue,/create_sdk_client/);assert.match(ads,/ad_campaigns/);assert.match(providers,/provider_connections/)});
test("iOS and Widget expose Today journey and official logo",async()=>{const arena=await readFile(new URL("../ios/Konsens/Features/ArenaView.swift",import.meta.url),"utf8");const models=await readFile(new URL("../ios/Konsens/Core/Models.swift",import.meta.url),"utf8");const widget=await readFile(new URL("../ios/KonsensWidget/KonsensWidget.swift",import.meta.url),"utf8");const watch=await readFile(new URL("../ios/KonsensWatch/KonsensWatchApp.swift",import.meta.url),"utf8");assert.match(arena,/get_my_daily_journey/);assert.match(arena,/get_my_konsens_score/);assert.match(models,/case \.wealth:"Aujourd’hui"/);assert.match(widget,/WidgetUniverse\.today/);assert.match(widget,/Image\("KonsensLogo"\)/);assert.match(watch,/dailyNext/);assert.match(watch,/score/)});
