"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { createClient } from "@supabase/supabase-js";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mxuevsspybxoovsutsbs.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_Xs7hyyDA2XUkbwXGGfSE2w_tARkgSL7");
type Campaign={id:string;name:string;status:string;placements:string[];starts_at:string;ends_at:string|null;advertisers:{name:string}|null;ad_creatives:Array<{id:string;sponsor_name:string;headline:string;body:string|null;cta_label:string;destination_url:string;is_active:boolean}>};

export default function AdsManager(){
 const[allowed,setAllowed]=useState<boolean|null>(null);const[campaigns,setCampaigns]=useState<Campaign[]>([]);const[status,setStatus]=useState("");const[form,setForm]=useState({sponsor:"",website:"",headline:"",body:"",cta:"Découvrir",placement:"feed_native",budget:"500",cpm:"8",days:"30"});
 const load=async()=>{const{data:auth}=await supabase.auth.getUser();if(!auth.user){setAllowed(false);return}const{data:p}=await supabase.from("profiles").select("role").eq("id",auth.user.id).single();if(!p||!["admin","moderator"].includes(p.role)){setAllowed(false);return}setAllowed(true);const{data}=await supabase.from("ad_campaigns").select("id,name,status,placements,starts_at,ends_at,advertisers(name),ad_creatives(id,sponsor_name,headline,body,cta_label,destination_url,is_active)").order("created_at",{ascending:false}).limit(30);setCampaigns((data??[]) as unknown as Campaign[])};
 useEffect(()=>{void load()},[]);
 const create=async(e:FormEvent)=>{e.preventDefault();setStatus("Création de la campagne…");const slug=`${form.sponsor.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,45)}-${Date.now().toString(36)}`;const{data:adv,error:aerr}=await supabase.from("advertisers").insert({name:form.sponsor,slug,website_url:form.website,status:"active"}).select("id").single();if(aerr||!adv){setStatus(aerr?.message??"Annonceur impossible");return}const end=new Date(Date.now()+Math.max(1,Number(form.days))*86400000).toISOString();const{data:camp,error:cerr}=await supabase.from("ad_campaigns").insert({advertiser_id:adv.id,name:`${form.sponsor} · ${form.headline.slice(0,35)}`,status:"active",placements:[form.placement],categories:[],starts_at:new Date().toISOString(),ends_at:end,budget_cents:Math.round(Number(form.budget)*100),cpm_cents:Math.round(Number(form.cpm)*100),priority:10,frequency_cap_per_session:2}).select("id").single();if(cerr||!camp){setStatus(cerr?.message??"Campagne impossible");return}const{error:rerr}=await supabase.from("ad_creatives").insert({campaign_id:camp.id,sponsor_name:form.sponsor,eyebrow:"SPONSORISÉ",headline:form.headline,body:form.body||null,cta_label:form.cta,destination_url:form.website,is_active:true});if(rerr){setStatus(rerr.message);return}setStatus("Campagne active. Elle est désormais éligible dans les emplacements Free de Konsens.");setForm({sponsor:"",website:"",headline:"",body:"",cta:"Découvrir",placement:"feed_native",budget:"500",cpm:"8",days:"30"});await load()};
 const toggle=async(c:Campaign)=>{const next=c.status==="active"?"paused":"active";await supabase.from("ad_campaigns").update({status:next,updated_at:new Date().toISOString()}).eq("id",c.id);await load()};
 if(allowed===null)return <main className="ads-console"><p>Chargement de Konsens Ads…</p></main>;if(!allowed)return <main className="ads-console"><h1>Accès réservé</h1><Link href="/">Retour</Link></main>;
 return <main className="ads-console"><header><div><span>KONSENS ADS · FIRST-PARTY AD SERVER</span><h1>Lancer une vraie campagne.</h1><p>Cette régie alimente directement les emplacements sponsorisés du Web et de l’iOS Free. Impressions et clics sont enregistrés dans Konsens Revenue.</p></div><div><Link href="/monetization">← Monétisation</Link><Link href="/">Application</Link></div></header>
 <div className="ads-layout"><form onSubmit={create} className="ads-form"><span>NOUVELLE CAMPAGNE</span><label>Annonceur<input required value={form.sponsor} onChange={e=>setForm({...form,sponsor:e.target.value})} placeholder="Nom de la marque"/></label><label>Destination<input required type="url" value={form.website} onChange={e=>setForm({...form,website:e.target.value})} placeholder="https://marque.fr/offre"/></label><label>Titre publicitaire<input required minLength={3} maxLength={140} value={form.headline} onChange={e=>setForm({...form,headline:e.target.value})} placeholder="Un message clair et utile"/></label><label>Texte<textarea maxLength={280} value={form.body} onChange={e=>setForm({...form,body:e.target.value})} placeholder="Pourquoi cette offre est pertinente dans ce contexte ?"/></label><div className="ads-pair"><label>CTA<input required value={form.cta} onChange={e=>setForm({...form,cta:e.target.value})}/></label><label>Placement<select value={form.placement} onChange={e=>setForm({...form,placement:e.target.value})}><option value="feed_native">Feed natif</option><option value="challenge_sponsor">Challenge sponsorisé</option><option value="post_prediction">Après prédiction</option></select></label></div><div className="ads-pair"><label>Budget indicatif (€)<input type="number" min="0" value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})}/></label><label>CPM indicatif (€)<input type="number" min="0" step="0.1" value={form.cpm} onChange={e=>setForm({...form,cpm:e.target.value})}/></label></div><label>Durée (jours)<input type="number" min="1" max="365" value={form.days} onChange={e=>setForm({...form,days:e.target.value})}/></label><button>Activer la campagne</button>{status&&<p>{status}</p>}<small>Les campagnes sont contextuelles par défaut. Elles ne nécessitent pas de profilage comportemental et n’achètent ni ne vendent de données personnelles.</small></form>
 <section className="ads-preview"><span>APERÇU LIVE</span><article><div><b>SPONSORISÉ</b><small>{form.sponsor||"Nom de la marque"}</small></div><h2>{form.headline||"Ton titre publicitaire apparaîtra ici."}</h2><p>{form.body||"Le format reprend le langage visuel de Konsens tout en restant explicitement identifié comme publicité."}</p><strong>{form.cta||"Découvrir"} ↗</strong></article><p>L’aperçu représente le composant natif. La diffusion réelle dépend du statut, de la période, du placement et des caps de fréquence.</p></section></div>
 <section className="ads-campaigns"><span>CAMPAGNES</span><h2>{campaigns.length} campagne(s) configurée(s)</h2>{campaigns.map(c=>{const cr=c.ad_creatives?.[0];return <article key={c.id}><div><b>{c.advertisers?.name??"Annonceur"}</b><span className={c.status}>{c.status}</span></div><h3>{cr?.headline??c.name}</h3><p>{c.placements.join(" · ")} · {new Date(c.starts_at).toLocaleDateString("fr-FR")} → {c.ends_at?new Date(c.ends_at).toLocaleDateString("fr-FR"):"sans fin"}</p><div><a href={cr?.destination_url??"#"} target="_blank" rel="noreferrer">Destination ↗</a><button onClick={()=>toggle(c)}>{c.status==="active"?"Mettre en pause":"Activer"}</button></div></article>})}</section></main>;
}
