"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@supabase/supabase-js";

type Whale={id:string;chain:string;address:string;display_name:string;wallet_kind:string;attribution_type:string;confidence_score:number;attribution_source_url:string|null;native_symbol:string|null;observable_balance_native:number|null;observable_value_eur:number|null;rank_hint:number|null;volume_30d_eur:number;transactions_30d:number;last_activity:string|null;source_updated_at:string|null};
type Follow={wallet_id:string;minimum_alert_eur:number;notifications_enabled:boolean};
type Tx={providerEventId:string;hash:string;from:string;to:string;eventType:string;direction:string;assetSymbol:string;assetAmount:number;estimatedValueEUR:number|null;blockTime:string;blockNumber:string;explorerUrl:string};
const url=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mxuevsspybxoovsutsbs.supabase.co";const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_Xs7hyyDA2XUkbwXGGfSE2w_tARkgSL7";const supabase=createClient(url,key);
const money=(n:number|null|undefined)=>n==null?"—":new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(n);
const short=(v:string)=>`${v.slice(0,7)}…${v.slice(-5)}`;

export default function BlockchainV2({premium,role}:{premium:boolean;role:string}){
 const unlocked=premium||role==="admin";const[whales,setWhales]=useState<Whale[]>([]);const[follows,setFollows]=useState<Follow[]>([]);const[selected,setSelected]=useState<Whale|null>(null);const[txs,setTxs]=useState<Tx[]>([]);const[provider,setProvider]=useState("");const[loading,setLoading]=useState(false);const[status,setStatus]=useState("");
 const load=async()=>{const{data:auth}=await supabase.auth.getUser();const[w,f]=await Promise.all([supabase.rpc("get_whale_leaderboard",{p_limit:25}),auth.user?supabase.from("wallet_follows").select("wallet_id,minimum_alert_eur,notifications_enabled").eq("user_id",auth.user.id):Promise.resolve({data:[]})]);const rows=((w.data??[]) as any[]).map(x=>({...x,confidence_score:Number(x.confidence_score),observable_balance_native:x.observable_balance_native==null?null:Number(x.observable_balance_native),observable_value_eur:x.observable_value_eur==null?null:Number(x.observable_value_eur),rank_hint:x.rank_hint==null?null:Number(x.rank_hint),volume_30d_eur:Number(x.volume_30d_eur??0),transactions_30d:Number(x.transactions_30d??0)}));setWhales(rows);setFollows(((f.data??[]) as any[]).map(x=>({...x,minimum_alert_eur:Number(x.minimum_alert_eur)})));setSelected(s=>s??rows[0]??null)};
 useEffect(()=>{void load()},[]);
 const followed=useMemo(()=>new Map(follows.map(f=>[f.wallet_id,f])),[follows]);
 const refreshWallet=async(w:Whale)=>{setSelected(w);setLoading(true);setStatus("Lecture de la blockchain…");setTxs([]);try{const session=(await supabase.auth.getSession()).data.session;if(!session)throw new Error("Reconnecte-toi pour lire la blockchain.");const r=await fetch(`${url}/functions/v1/blockchain-data?wallet_id=${encodeURIComponent(w.id)}&address=${encodeURIComponent(w.address)}`,{headers:{authorization:`Bearer ${session.access_token}`,apikey:key}});const body=await r.json();if(!r.ok)throw new Error(body.detail??body.error??"Flux blockchain indisponible");setTxs(body.transactions??[]);setProvider(body.provider??"");setStatus(body.persistedForAlerts?"Flux synchronisé · alertes Premium armées.":"Flux public synchronisé.")}catch(e){setStatus(e instanceof Error?e.message:"Flux blockchain indisponible")}setLoading(false)};
 const toggleFollow=async(w:Whale)=>{if(!unlocked){setStatus("Le suivi et les alertes de portefeuilles sont réservés à Premium.");return}const{data:auth}=await supabase.auth.getUser();if(!auth.user)return;const active=followed.has(w.id);const q=active?await supabase.from("wallet_follows").delete().eq("user_id",auth.user.id).eq("wallet_id",w.id):await supabase.from("wallet_follows").insert({user_id:auth.user.id,wallet_id:w.id,minimum_alert_eur:25000,notifications_enabled:true});if(q.error){setStatus(q.error.message.includes("premium")?"Premium requis pour suivre ce portefeuille.":q.error.message);return}setStatus(active?"Portefeuille retiré des alertes.":"Portefeuille suivi · alerte à partir de 25 000 €.");await load();if(!active)await refreshWallet(w)};
 const setAlert=async(w:Whale,value:number)=>{if(!unlocked)return;const{error}=await supabase.rpc("set_wallet_alert",{p_wallet_id:w.id,p_minimum_alert_eur:value,p_enabled:true});if(error){setStatus(error.message);return}setFollows(old=>old.map(f=>f.wallet_id===w.id?{...f,minimum_alert_eur:value,notifications_enabled:true}:f));setStatus(`Alerte ${w.display_name} réglée à ${money(value)}.`)};
 return <section className="blockchain-v2"><header className="chain-hero"><div><span>KONSENS TRANSPARENCY · CHAÎNE PUBLIQUE</span><h1>Voir les mouvements.<br/><em>Vérifier à la source.</em></h1><p>Konsens agrège des adresses publiquement attribuées à des protocoles, bridges, exchanges ou institutions. Les transactions restent vérifiables sur l’explorateur. Une adresse n’est jamais présentée comme l’identité d’une personne sans attribution publique sourcée.</p></div><aside><b>{whales.length}</b><span>grands portefeuilles référencés</span><small>{unlocked?"PREMIUM · ALERTES ACTIVES":"LECTURE PUBLIQUE · ALERTES PREMIUM"}</small></aside></header>
 <div className="chain-layout"><section className="whale-list"><header><div><span>WHALE WATCH</span><h2>Grands acteurs on-chain</h2></div><small>Ethereum · données publiques</small></header>{whales.map((w,i)=>{const f=followed.get(w.id);return <article className={selected?.id===w.id?"whale-card active":"whale-card"} key={w.id}><button className="whale-main" onClick={()=>refreshWallet(w)}><i>{i+1}</i><div><b>{w.display_name}</b><span>{w.wallet_kind.toUpperCase()} · {short(w.address)}</span><small>Attribution {w.confidence_score}% · {w.transactions_30d} tx suivies / 30 j</small></div><strong>{w.observable_value_eur?money(w.observable_value_eur):w.observable_balance_native!=null?`${w.observable_balance_native.toLocaleString("fr-FR")} ${w.native_symbol??""}`:"PUBLIC"}</strong></button><div className="whale-actions"><button className={f?"follow active":"follow"} onClick={()=>toggleFollow(w)}>{f?"★ Suivi":"☆ Suivre"}</button>{w.attribution_source_url&&<a href={w.attribution_source_url} target="_blank" rel="noreferrer">Source ↗</a>}</div>{f&&<div className="alert-level"><span>Alerte transaction</span>{[10000,25000,50000,100000].map(v=><button className={f.minimum_alert_eur===v?"active":""} key={v} onClick={()=>setAlert(w,v)}>{v>=1000?`${v/1000}k`:v} €</button>)}</div>}</article>})}</section>
 <section className="chain-terminal"><header>{selected?<><div><span>ADRESSE SÉLECTIONNÉE</span><h2>{selected.display_name}</h2><code>{selected.address}</code></div><button onClick={()=>refreshWallet(selected)} disabled={loading}>{loading?"Synchronisation…":"↻ Actualiser"}</button></>:<h2>Sélectionne un portefeuille</h2>}</header>{provider&&<div className="chain-provider"><i/> {provider} · données publiques vérifiables</div>}{txs.length===0?<div className="chain-empty"><b>◈</b><h3>{loading?"Lecture en cours…":"Aucune transaction chargée"}</h3><p>Ouvre un portefeuille pour lire ses dernières transactions publiques. Les alertes automatiques sont exclusivement Premium.</p></div>:<div className="tx-list">{txs.map(tx=><a href={tx.explorerUrl} target="_blank" rel="noreferrer" key={tx.providerEventId}><i className={tx.direction==="in"?"in":"out"}>{tx.direction==="in"?"↓":"↑"}</i><div><b>{tx.direction==="in"?"Réception":"Envoi"} · {tx.assetSymbol}</b><span>{tx.assetAmount.toLocaleString("fr-FR",{maximumFractionDigits:6})} {tx.assetSymbol}</span><small>{new Date(tx.blockTime).toLocaleString("fr-FR")} · bloc {tx.blockNumber}</small></div><strong>{tx.estimatedValueEUR!=null?money(tx.estimatedValueEUR):"Valeur € n/d"}</strong><em>↗</em></a>)}</div>}{status&&<p className="chain-status">{status}</p>}</section></div>
 {!unlocked&&<section className="chain-premium"><div><span>PREMIUM EXCLUSIF</span><h2>Suis jusqu’à 10 portefeuilles et reçois leurs gros mouvements.</h2><p>Seuil personnalisable par portefeuille, alertes sur transactions, accès direct à l’explorateur et historique synchronisé. Aucun wallet privé ni donnée bancaire n’est collecté.</p></div><b>4,99 € / mois</b></section>}
 </section>
}
