"use client";

import { useEffect, useState } from "react";
import { createClient } from "@supabase/supabase-js";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mxuevsspybxoovsutsbs.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_Xs7hyyDA2XUkbwXGGfSE2w_tARkgSL7");
type Journal={id:string;decision_type:"prediction"|"investment";asset_id:string|null;market_id:string|null;outcome:string|null;credits:number;entry_price:number|null;decision_at:string;reviewed_at:string|null};
const reasons=[['news','Actualité'],['analysis','Analyse'],['lesson','Ce que j’ai appris'],['consensus','Consensus'],['intuition','Intuition'],['coach','Coach Konsens']];

export default function DecisionReflection(){
 const[entry,setEntry]=useState<Journal|null>(null),[reason,setReason]=useState('intuition'),[confidence,setConfidence]=useState(60),[thesis,setThesis]=useState(''),[label,setLabel]=useState(''),[saving,setSaving]=useState(false);
 useEffect(()=>{const open=()=>void loadLatest();window.addEventListener('konsens:trade',open);return()=>window.removeEventListener('konsens:trade',open)},[]);
 const loadLatest=async()=>{const{data:auth}=await supabase.auth.getUser();if(!auth.user)return;await new Promise(r=>setTimeout(r,180));const{data}=await supabase.from('decision_journal').select('id,decision_type,asset_id,market_id,outcome,credits,entry_price,decision_at,reviewed_at').eq('user_id',auth.user.id).order('decision_at',{ascending:false}).limit(5);const candidate=(data??[]).find(row=>!row.reviewed_at);if(!candidate)return;const row={...candidate,credits:Number(candidate.credits),entry_price:candidate.entry_price==null?null:Number(candidate.entry_price)} as Journal;setEntry(row);setReason('intuition');setConfidence(60);setThesis('');if(row.market_id){const{data:m}=await supabase.from('markets').select('question').eq('id',row.market_id).maybeSingle();setLabel(m?.question??'Prédiction')}else if(row.asset_id){const{data:a}=await supabase.from('assets').select('symbol,name').eq('id',row.asset_id).maybeSingle();setLabel(a?`${a.symbol} · ${a.name}`:'Investissement')}else setLabel('Décision')};
 const save=async()=>{if(!entry||saving)return;setSaving(true);const{error}=await supabase.from('decision_journal').update({reason_code:reason,confidence,thesis:thesis.trim()||null,reviewed_at:new Date().toISOString()}).eq('id',entry.id);if(!error){setEntry(null);window.dispatchEvent(new Event('konsens:reflection'))}setSaving(false)};
 const skip=async()=>{if(!entry)return;await supabase.from('decision_journal').update({reviewed_at:new Date().toISOString()}).eq('id',entry.id);setEntry(null)};
 if(!entry)return null;
 return <div className="reflection-backdrop"><section className="decision-reflection"><button className="reflection-close" onClick={skip} aria-label="Fermer">×</button><span>JOURNAL DE DÉCISION · 20 SECONDES</span><h2>Pourquoi as-tu pris cette décision ?</h2><p className="reflection-target">{label}</p><div className="reflection-reasons">{reasons.map(([id,text])=><button key={id} className={reason===id?'active':''} onClick={()=>setReason(id)}>{text}</button>)}</div><label className="reflection-confidence"><span>Ton niveau de confiance <b>{confidence}%</b></span><input type="range" min="10" max="95" step="5" value={confidence} onChange={e=>setConfidence(Number(e.target.value))}/><small>Ce n’est pas une note : dans le temps, Konsens comparera cette confiance aux résultats.</small></label><label className="reflection-thesis"><span>Une phrase pour ton futur toi <small>facultatif</small></span><textarea maxLength={240} value={thesis} onChange={e=>setThesis(e.target.value)} placeholder="Ex. Je pense que le marché sous-estime encore le risque de taux…"/></label><footer><button className="skip" onClick={skip}>Plus tard</button><button className="save" disabled={saving} onClick={save}>{saving?'Enregistrement…':'Enregistrer mon raisonnement'}</button></footer><small className="reflection-note">Konsens utilise ce journal uniquement pour ton apprentissage et ton Coach personnel.</small></section></div>
}
