"use client";

/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useMemo, useState } from "react";
import { createClient, type User } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL ?? "https://mxuevsspybxoovsutsbs.supabase.co",
  process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? "sb_publishable_Xs7hyyDA2XUkbwXGGfSE2w_tARkgSL7",
);

type Screen = "wealth" | "play" | "invest" | "learn" | "profile" | "admin";
type Profile = { username:string; first_name:string|null; last_name:string|null; birth_date:string|null; email:string|null; role:string; onboarding_completed_at:string|null; subscription_tier:"free"|"premium"; journey_mode:"balanced"|"play"|"learn"; risk_acknowledged_at:string|null };
type Wealth = { cash_value:number; investments_value:number; bets_value:number; total_value:number };
type Asset = { id:string; symbol:string; name:string; kind:string; price:number };
type Market = { id:string; question:string; category:string; yes_probability:number; closes_at:string };
type Lesson = { id:string; slug:string; title:string; summary:string; concept:string; xp_reward:number };

const emptyWealth:Wealth = { cash_value:0, investments_value:0, bets_value:0, total_value:0 };
const fmt = (n:number) => new Intl.NumberFormat("fr-FR", { maximumFractionDigits:0 }).format(n);

function Icon({name}:{name:"home"|"play"|"chart"|"book"|"user"|"lock"|"shield"}){
  const d={home:"M3 11 12 4l9 7v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z",play:"M8 5v14l11-7z",chart:"M4 19V9m6 10V5m6 14v-7m4 7H2",book:"M4 5a4 4 0 0 1 4-2h4v17H8a4 4 0 0 0-4 2zm16 0a4 4 0 0 0-4-2h-4v17h4a4 4 0 0 1 4 2z",user:"M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm7 9a7 7 0 0 0-14 0",lock:"M7 11V8a5 5 0 0 1 10 0v3m-9 0h8a2 2 0 0 1 2 2v7H6v-7a2 2 0 0 1 2-2z",shield:"M12 3l8 3v5c0 5-3.4 8.7-8 10-4.6-1.3-8-5-8-10V6z"}[name];
  return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={d}/></svg>;
}

function Brand(){return <div className="f-brand"><span className="f-mark"><b>K</b><i/><i/><i/></span><div><strong>Konsens</strong><small>PRÉDIRE · APPRENDRE · INVESTIR</small></div></div>}

export default function FinanceShell(){
  const [user,setUser]=useState<User|null>(null); const [loading,setLoading]=useState(true); const [profile,setProfile]=useState<Profile|null>(null); const [screen,setScreen]=useState<Screen>("wealth");
  const [wealth,setWealth]=useState<Wealth>(emptyWealth); const [assets,setAssets]=useState<Asset[]>([]); const [markets,setMarkets]=useState<Market[]>([]); const [lessons,setLessons]=useState<Lesson[]>([]); const [toast,setToast]=useState(""); const [refresh,setRefresh]=useState(0);
  useEffect(()=>{void supabase.auth.getUser().then(({data})=>{setUser(data.user);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_event,session)=>{setUser(session?.user??null);setLoading(false)});return()=>data.subscription.unsubscribe()},[]);
  useEffect(()=>{if(!user){setProfile(null);return}let active=true;void(async()=>{const [p,w,l,m,a]=await Promise.all([
    supabase.from("profiles").select("username,first_name,last_name,birth_date,email,role,onboarding_completed_at,subscription_tier,journey_mode,risk_acknowledged_at").eq("id",user.id).single(),
    supabase.rpc("get_my_wealth_snapshot"),
    supabase.from("learning_modules").select("id,slug,title,summary,concept,xp_reward").eq("is_active",true).order("position"),
    supabase.from("markets").select("id,question,category,yes_probability,closes_at").eq("status","open").order("closes_at").limit(12),
    supabase.from("assets").select("id,symbol,name,kind").eq("is_active",true).order("symbol")
  ]);if(!active)return;if(p.data)setProfile(p.data as Profile);const ws=Array.isArray(w.data)?w.data[0]:w.data;if(ws)setWealth({cash_value:Number(ws.cash_value),investments_value:Number(ws.investments_value),bets_value:Number(ws.bets_value),total_value:Number(ws.total_value)});setLessons((l.data??[]) as Lesson[]);setMarkets(((m.data??[]) as Omit<Market,"yes_probability">[] & {yes_probability:number}[]).map(x=>({...x,yes_probability:Number(x.yes_probability)})) as Market[]);const base=(a.data??[]) as Omit<Asset,"price">[];const priced=await Promise.all(base.map(async x=>{const q=await supabase.from("price_history").select("price").eq("asset_id",x.id).order("observed_at",{ascending:false}).limit(1).maybeSingle();return {...x,price:Number(q.data?.price??0)}}));if(active)setAssets(priced)})();return()=>{active=false}},[user,refresh]);
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2600)};
  if(loading)return <main className="f-loading"><Brand/><span/></main>;
  if(!user)return <Auth/>;
  if(!profile?.onboarding_completed_at)return <Onboarding user={user} done={()=>setRefresh(x=>x+1)}/>;
  const perf=((wealth.total_value-1000)/1000)*100;
  const trade=async(kind:"asset"|"bet",id:string,amount:number,outcome?:"yes"|"no")=>{const payload=kind==="asset"?{user_id:user.id,asset_id:id,market_id:null,side:"buy",outcome:null,credits:amount,idempotency_key:crypto.randomUUID()}:{user_id:user.id,asset_id:null,market_id:id,side:"buy",outcome,credits:amount,idempotency_key:crypto.randomUUID()};const {data,error}=await supabase.from("trade_orders").insert(payload).select("status,rejection_reason").single();if(error||data?.status!=="executed"){notify(data?.rejection_reason??error?.message??"Ordre refusé");return}notify(kind==="asset"?"Investissement simulé exécuté":"Pari en Koins enregistré");setRefresh(x=>x+1)};
  const acknowledge=async()=>{await supabase.from("profiles").update({risk_acknowledged_at:new Date().toISOString()}).eq("id",user.id);setRefresh(x=>x+1)};
  return <main className="finance-app"><div className="f-ambient f-a"/><div className="f-ambient f-b"/><header className="f-float-head"><button onClick={()=>setScreen("wealth")} className="f-brand-button"><Brand/></button><button onClick={()=>setScreen("profile")} className="f-wealth-pill"><span>{profile.subscription_tier==="premium"?"PREMIUM":"PATRIMOINE"}</span><strong>{fmt(wealth.total_value)} <small>Koins</small></strong><i className={perf>=0?"up":"down"}>{perf>=0?"+":""}{perf.toFixed(1)}%</i></button></header>
  <section className="beta-content finance-content">
    {screen==="wealth"&&<WealthHome profile={profile} wealth={wealth} perf={perf} lessons={lessons} markets={markets} assets={assets} go={setScreen} acknowledge={acknowledge}/>} 
    {screen==="play"&&<Play markets={markets} cash={wealth.cash_value} trade={trade}/>} 
    {screen==="invest"&&<Invest assets={assets} cash={wealth.cash_value} trade={trade} premium={profile.subscription_tier==="premium"}/>} 
    {screen==="learn"&&<Learn lessons={lessons}/>} 
    {screen==="profile"&&<ProfileView profile={profile} wealth={wealth} go={setScreen}/>} 
    {screen==="admin"&&profile.role==="admin"&&<Admin/>}
  </section><Dock screen={screen} go={setScreen}/>{toast&&<div className="f-toast">{toast}</div>}</main>
}

function Dock({screen,go}:{screen:Screen;go:(s:Screen)=>void}){const items:[Screen,string,"home"|"play"|"chart"|"book"|"user"][]=[["wealth","Patrimoine","home"],["play","Jouer","play"],["invest","Investir","chart"],["learn","Apprendre","book"],["profile","Profil","user"]];return <nav className="f-dock" aria-label="Navigation principale">{items.map(([id,label,icon])=><button key={id} onClick={()=>go(id)} className={screen===id?"active":""}><Icon name={icon}/><span>{label}</span></button>)}</nav>}

function WealthHome({profile,wealth,perf,lessons,markets,assets,go,acknowledge}:{profile:Profile;wealth:Wealth;perf:number;lessons:Lesson[];markets:Market[];assets:Asset[];go:(s:Screen)=>void;acknowledge:()=>void}){return <><section className="f-hero"><div className="f-hero-copy"><span className="eyebrow">TON LABORATOIRE FINANCIER</span><h1>Fais grandir ton patrimoine.<br/><em>Comprends chaque décision.</em></h1><p>1 000 Koins au départ. Aucun argent réel. Chaque pari et chaque investissement modifie ton patrimoine virtuel et t’apprend ce que le risque coûte vraiment.</p><div className="hero-actions"><button onClick={()=>go("invest")}>Investir en simulation</button><button onClick={()=>go("play")}>Tester mon instinct</button></div></div><article className="wealth-card"><div><span>PATRIMOINE TOTAL</span><b className={perf>=0?"positive":"negative"}>{perf>=0?"+":""}{perf.toFixed(1)}%</b></div><strong>{fmt(wealth.total_value)} <small>Koins</small></strong><div className="wealth-line"><svg viewBox="0 0 420 90" preserveAspectRatio="none"><path d="M0 62 C70 60 105 60 150 59 S250 58 310 58 S370 58 420 58"/></svg><i>Départ 1 000</i></div><div className="wealth-split"><p><span>Disponible</span><b>{fmt(wealth.cash_value)}</b></p><p><span>Investi</span><b>{fmt(wealth.investments_value)}</b></p><p><span>En paris</span><b>{fmt(wealth.bets_value)}</b></p></div></article></section>
  {!profile.risk_acknowledged_at&&<section className="risk-banner"><Icon name="shield"/><div><strong>Le but n’est pas seulement de gagner.</strong><p>Konsens te montre aussi la perte, la volatilité et le coût d’une mauvaise décision. Les Koins n’ont aucune valeur monétaire et ne sont jamais convertibles.</p></div><button onClick={acknowledge}>J’ai compris</button></section>}
  <section className="f-grid"><button className="feature-card play-card" onClick={()=>go("play")}><span>JOUER</span><strong>{markets.length?`${markets.length} marchés ouverts`:"Tes prochains défis"}</strong><p>Prends position OUI/NON et observe ce que le risque fait à ton patrimoine.</p><i>Tester mon instinct →</i></button><button className="feature-card invest-card" onClick={()=>go("invest")}><span>INVESTIR</span><strong>{assets.length} supports école</strong><p>Construis un portefeuille virtuel avant d’aborder les vrais marchés.</p><i>Construire mon portefeuille →</i></button><button className="feature-card learn-card" onClick={()=>go("learn")}><span>APPRENDRE</span><strong>{lessons.length} cours disponibles</strong><p>Des notions courtes reliées directement aux décisions que tu prends.</p><i>Comprendre avant d’agir →</i></button></section>
  <PremiumStrip premium={profile.subscription_tier==="premium"}/></>}

function Play({markets,cash,trade}:{markets:Market[];cash:number;trade:(kind:"asset"|"bet",id:string,amount:number,outcome?:"yes"|"no")=>Promise<void>}){const[amount,setAmount]=useState(100);return <section className="f-page"><PageTitle tag="PRÉDICTION" title="Joue ton instinct. Mesure le risque." text={`Solde disponible : ${fmt(cash)} Koins. Un pari peut accélérer ton patrimoine comme l’amputer.`}/><Amount value={amount} set={setAmount}/>{markets.length===0?<Empty title="Aucun marché vérifié ouvert" text="Les paris ne sont publiés qu’après validation de la question, de la source et de la règle de résolution."/>:<div className="market-grid">{markets.map(m=><article className="market-card" key={m.id}><span>{m.category.toUpperCase()}</span><h2>{m.question}</h2><div className="consensus"><b>{Math.round(m.yes_probability*100)}% OUI</b><i/><b>{Math.round((1-m.yes_probability)*100)}% NON</b></div><small>Clôture {new Date(m.closes_at).toLocaleDateString("fr-FR")}</small><div className="market-actions"><button onClick={()=>trade("bet",m.id,amount,"yes")}>OUI · {amount}</button><button onClick={()=>trade("bet",m.id,amount,"no")}>NON · {amount}</button></div></article>)}</div>}<RiskNote/></section>}

function Invest({assets,cash,trade,premium}:{assets:Asset[];cash:number;trade:(kind:"asset"|"bet",id:string,amount:number)=>Promise<void>;premium:boolean}){const[amount,setAmount]=useState(100);return <section className="f-page"><PageTitle tag="INVESTISSEMENT" title="Apprends avec un vrai réflexe de portefeuille." text={`Tu disposes de ${fmt(cash)} Koins. Les cotations ci-dessous sont des valeurs d’entraînement, pas des cours de marché.`}/><Amount value={amount} set={setAmount}/><div className="asset-list">{assets.map((a,index)=><article key={a.id}><span className={`asset-orb o${index%3}`}>{a.symbol.slice(0,2)}</span><div><small>{a.kind.toUpperCase()} · SIMULATION</small><h2>{a.name}</h2><p>Support pédagogique Konsens · valeur école {a.price.toFixed(2)}</p></div><strong>{a.price.toFixed(2)}</strong><button disabled={cash<amount} onClick={()=>trade("asset",a.id,amount)}>Investir {amount}</button></article>)}</div><section className="premium-panel"><div><span>PREMIUM · 4,99 €/MOIS</span><h2>Du simulateur aux vrais marchés.</h2><p>Flux financiers via API, tendances enrichies, prédictif et détail des portefeuilles publics. L’achat réel d’actifs reste hors de Konsens.</p></div><button>{premium?"Premium actif":"Bientôt disponible"}</button></section><RiskNote/></section>}

function Learn({lessons}:{lessons:Lesson[]}){const[selected,setSelected]=useState<Lesson|null>(null);return <section className="f-page"><PageTitle tag="KONSENS ACADEMY" title="Comprendre avant de risquer." text="Des cours courts, reliés à ce que tu vois dans ton portefeuille et dans les prédictions."/><div className="lesson-list">{lessons.map((l,i)=><button key={l.id} onClick={()=>setSelected(l)}><span>{String(i+1).padStart(2,"0")}</span><div><small>+{l.xp_reward} XP · 5 MIN</small><h2>{l.title}</h2><p>{l.summary}</p></div><b>→</b></button>)}</div>{selected&&<div className="lesson-modal" onClick={()=>setSelected(null)} role="presentation"><article onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><span>COURS · {selected.title}</span><h2>{selected.title}</h2><p>{selected.summary}</p><div>{selected.concept}</div><button className="primary" onClick={()=>setSelected(null)}>J’ai compris</button></article></div>}</section>}

function ProfileView({profile,wealth,go}:{profile:Profile;wealth:Wealth;go:(s:Screen)=>void}){return <section className="f-page profile-new"><PageTitle tag="MON ESPACE" title={`@${profile.username}`} text={`${profile.subscription_tier==="premium"?"Konsens Premium":"Konsens Gratuit"} · patrimoine ${fmt(wealth.total_value)} Koins`}/><div className="profile-cards"><article><span>PARCOURS</span><h2>{profile.journey_mode==="play"?"Joueur":profile.journey_mode==="learn"?"Apprenant":"Équilibré"}</h2><p>Konsens adapte progressivement les contenus entre stratégie, finance et apprentissage.</p></article><article><span>ABONNEMENT</span><h2>{profile.subscription_tier==="premium"?"Premium":"Gratuit + publicité"}</h2><p>Premium à 4,99 €/mois : analyses enrichies, portefeuilles détaillés et futurs flux marchés.</p></article></div>{profile.role==="admin"&&<button className="admin-entry" onClick={()=>go("admin")}>Ouvrir le centre d’administration →</button>}<button className="logout" onClick={()=>supabase.auth.signOut()}>Se déconnecter</button></section>}

function Admin(){return <section className="f-page"><PageTitle tag="ADMINISTRATION" title="Centre de pilotage" text="La monétisation, les campagnes et le SDK restent pilotés depuis l’espace de contrôle."/><a className="admin-link" href="/monetization">Ouvrir Konsens Monetization →</a></section>}

function PremiumStrip({premium}:{premium:boolean}){return <section className="premium-strip"><Icon name="lock"/><div><span>KONSENS PREMIUM</span><strong>{premium?"Premium actif":"Passe du signal à l’analyse · 4,99 €/mois"}</strong><p>Sans pub · détails des portefeuilles · prédictif · futurs flux financiers API.</p></div><button>{premium?"Actif":"Découvrir"}</button></section>}
function RiskNote(){return <div className="risk-note"><Icon name="shield"/><p><strong>Risque visible, argent fictif.</strong> Une forte performance virtuelle peut être suivie d’une perte importante. Les Koins ne sont ni achetables, ni convertibles, ni retirable en argent.</p></div>}
function PageTitle({tag,title,text}:{tag:string;title:string;text:string}){return <header className="f-page-title"><span>{tag}</span><h1>{title}</h1><p>{text}</p></header>}
function Empty({title,text}:{title:string;text:string}){return <div className="f-empty"><span>◎</span><h2>{title}</h2><p>{text}</p></div>}
function Amount({value,set}:{value:number;set:(n:number)=>void}){return <div className="amount-picker"><span>MISE / INVESTISSEMENT</span>{[25,50,100,250].map(n=><button className={value===n?"active":""} onClick={()=>set(n)} key={n}>{n}</button>)}<small>Koins</small></div>}

function Auth(){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[mode,setMode]=useState<"signup"|"login">("login");const[status,setStatus]=useState("");const social=async(provider:"google"|"apple")=>{const{error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo:location.origin}});if(error)setStatus(error.message)};const submit=async(e:React.FormEvent)=>{e.preventDefault();setStatus("Connexion…");const result=mode==="signup"?await supabase.auth.signUp({email,password,options:{emailRedirectTo:location.origin}}):await supabase.auth.signInWithPassword({email,password});setStatus(result.error?.message??(mode==="signup"?"Vérifie ta boîte mail pour confirmer ton inscription.":"Connecté."))};return <main className="finance-auth"><section className="auth-pitch"><Brand/><span>1 000 KOINS OFFERTS</span><h1>Ton argent fictif.<br/><em>De vraies leçons.</em></h1><p>Prédis, investis, apprends. Construis un patrimoine virtuel et découvre ce que tes décisions peuvent réellement coûter.</p><div className="auth-proof"><b>0 € réel</b><b>Finance expliquée</b><b>Risque visible</b></div></section><section className="auth-panel"><span>BIENVENUE</span><h2>{mode==="login"?"Reprendre mon parcours":"Créer mon portefeuille"}</h2><div className="social"><button onClick={()=>social("apple")}>Continuer avec Apple</button><button onClick={()=>social("google")}>Continuer avec Google</button></div><i>ou</i><form onSubmit={submit}><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Mot de passe<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary">{mode==="login"?"Me connecter":"Créer mon compte"}</button></form>{status&&<p>{status}</p>}<button className="auth-switch" onClick={()=>setMode(mode==="login"?"signup":"login")}>{mode==="login"?"Créer un compte":"J’ai déjà un compte"}</button><small>Les Koins sont une unité virtuelle sans valeur monétaire. Konsens ne permet aucun dépôt, retrait ou conversion en argent.</small></section></main>}

function Onboarding({user,done}:{user:User;done:()=>void}){const[today]=useState(()=>Date.now());const[p,setP]=useState({username:"",first_name:"",last_name:"",birth_date:"",email:user.email??""});const age=useMemo(()=>p.birth_date?Math.floor((today-new Date(p.birth_date).getTime())/31557600000):0,[p.birth_date,today]);const save=async()=>{if(age<18)return;const{error}=await supabase.from("profiles").update({...p,onboarding_completed_at:new Date().toISOString(),journey_mode:"balanced"}).eq("id",user.id);if(!error)done()};return <main className="finance-auth onboarding-new"><section className="auth-pitch"><Brand/><span>TON POINT DE DÉPART</span><h1>1 000 Koins.<br/><em>À toi de décider.</em></h1><p>Tu pourras les conserver, les investir ou les engager dans des prédictions. Ton patrimoine suivra chaque choix.</p></section><section className="auth-panel"><span>PROFIL</span><h2>Créons ton identité Konsens</h2><label>Pseudo public<input value={p.username} onChange={e=>setP({...p,username:e.target.value.replace(/[^a-zA-Z0-9_]/g,"")})}/></label><div className="field-pair"><label>Prénom<input value={p.first_name} onChange={e=>setP({...p,first_name:e.target.value})}/></label><label>Nom<input value={p.last_name} onChange={e=>setP({...p,last_name:e.target.value})}/></label></div><label>Date de naissance<input type="date" value={p.birth_date} onChange={e=>setP({...p,birth_date:e.target.value})}/></label>{p.birth_date&&age<18&&<p>Konsens est actuellement réservé aux personnes majeures.</p>}<button className="primary" disabled={p.username.length<3||!p.first_name||!p.last_name||age<18} onClick={save}>Recevoir mes 1 000 Koins</button></section></main>}
