"use client";

/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useMemo, useState } from "react";
import { createClient, type User } from "@supabase/supabase-js";
import AcademyV2 from "./academy-v2";
import LiveFinanceV2 from "./live-finance-v2";
import PredictionV2 from "./prediction-v2";
import PremiumV2 from "./premium-v2";
import BlockchainV2 from "./blockchain-v2";
import NotificationCenter from "./notification-center";
import TodayV3 from "./today-v3";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mxuevsspybxoovsutsbs.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_Xs7hyyDA2XUkbwXGGfSE2w_tARkgSL7");
type Screen="wealth"|"play"|"invest"|"learn"|"profile"|"network"|"admin";
type Profile={username:string;first_name:string|null;last_name:string|null;birth_date:string|null;email:string|null;role:string;onboarding_completed_at:string|null;subscription_tier:"free"|"premium";journey_mode:"balanced"|"play"|"learn";risk_acknowledged_at:string|null;financial_archetype?:string|null};
type Wealth={cash_value:number;investments_value:number;bets_value:number;total_value:number};
const emptyWealth:Wealth={cash_value:0,investments_value:0,bets_value:0,total_value:0},fmt=(n:number)=>new Intl.NumberFormat("fr-FR",{maximumFractionDigits:0}).format(n);
function Icon({name}:{name:"home"|"play"|"chart"|"book"|"user"}){const d={home:"M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18zm0 4v5l3 2",play:"M8 5v14l11-7z",chart:"M4 19V9m6 10V5m6 14v-7m4 7H2",book:"M4 5a4 4 0 0 1 4-2h4v17H8a4 4 0 0 0-4 2zm16 0a4 4 0 0 0-4-2h-4v17h4a4 4 0 0 1 4 2z",user:"M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm7 9a7 7 0 0 0-14 0"}[name];return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={d}/></svg>}
function Brand(){return <div className="f-brand"><img className="konsens-official-logo" src="/konsens-logo.png" alt="Logo Konsens"/><div><strong>Konsens</strong><small>ENTRAÎNE TON INTELLIGENCE FINANCIÈRE</small></div></div>}

export default function FinanceShell(){
 const[user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[profile,setProfile]=useState<Profile|null>(null),[screen,setScreen]=useState<Screen>("wealth"),[wealth,setWealth]=useState<Wealth>(emptyWealth),[toast,setToast]=useState(""),[refresh,setRefresh]=useState(0);
 useEffect(()=>{void supabase.auth.getUser().then(({data})=>{setUser(data.user);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_event,session)=>{setUser(session?.user??null);setLoading(false)});return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{const listener=()=>setRefresh(x=>x+1);window.addEventListener("konsens:trade",listener);window.addEventListener("konsens:subscription",listener);return()=>{window.removeEventListener("konsens:trade",listener);window.removeEventListener("konsens:subscription",listener)}},[]);
 useEffect(()=>{if(!user){setProfile(null);return}let active=true;void(async()=>{await supabase.rpc("refresh_my_premium_status");const[p,w]=await Promise.all([supabase.from("profiles").select("username,first_name,last_name,birth_date,email,role,onboarding_completed_at,subscription_tier,journey_mode,risk_acknowledged_at,financial_archetype").eq("id",user.id).single(),supabase.rpc("get_my_wealth_snapshot")]);if(!active)return;if(p.data)setProfile(p.data as Profile);const ws=Array.isArray(w.data)?w.data[0]:w.data;if(ws)setWealth({cash_value:Number(ws.cash_value),investments_value:Number(ws.investments_value),bets_value:Number(ws.bets_value),total_value:Number(ws.total_value)})})();return()=>{active=false}},[user,refresh]);
 const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2600)};
 if(loading)return <main className="f-loading"><Brand/><span/></main>;
 if(!user)return <Auth/>;
 if(!profile?.onboarding_completed_at)return <Onboarding user={user} done={()=>setRefresh(x=>x+1)}/>;
 const perf=(wealth.total_value-1000)/1000*100;
 const navigate=(route:"play"|"invest"|"profile")=>setScreen(route);
 const journeyNavigate=(route:"play"|"invest"|"learn"|"profile"|"network")=>setScreen(route);
 return <main className="finance-app"><div className="f-ambient f-a"/><div className="f-ambient f-b"/><header className="f-float-head"><button onClick={()=>setScreen("wealth")} className="f-brand-button"><Brand/></button><div className="head-actions"><NotificationCenter userId={user.id} onNavigate={navigate}/><button onClick={()=>setScreen("profile")} className="f-wealth-pill"><span>{profile.subscription_tier==="premium"?"PREMIUM":"MES KOINS"}</span><strong>{fmt(wealth.total_value)} <small>Koins</small></strong><i className={perf>=0?"up":"down"}>{perf>=0?"+":""}{perf.toFixed(1)}%</i></button></div></header><section className="beta-content finance-content">{screen==="wealth"&&<TodayV3 username={profile.username} premium={profile.subscription_tier==="premium"} wealth={wealth.total_value} onNavigate={journeyNavigate}/>} {screen==="play"&&<PredictionV2 cash={wealth.cash_value} role={profile.role}/>} {screen==="invest"&&<LiveFinanceV2 cash={wealth.cash_value} premium={profile.subscription_tier==="premium"}/>} {screen==="learn"&&<AcademyV2/>} {screen==="profile"&&<ProfileView userId={user.id} profile={profile} wealth={wealth} go={setScreen}/>} {screen==="network"&&<BlockchainV2 premium={profile.subscription_tier==="premium"} role={profile.role}/>} {screen==="admin"&&profile.role==="admin"&&<Admin/>}</section><Dock screen={screen} go={setScreen}/>{toast&&<div className="f-toast">{toast}</div>}</main>
}
function Dock({screen,go}:{screen:Screen;go:(s:Screen)=>void}){const items:[Screen,string,"home"|"play"|"chart"|"book"|"user"][]=[["wealth","Aujourd’hui","home"],["play","Prédire","play"],["invest","Décider","chart"],["learn","Apprendre","book"],["profile","Moi","user"]];return <nav className="f-dock" aria-label="Navigation principale">{items.map(([id,label,icon])=><button key={id} onClick={()=>go(id)} className={screen===id?"active":""}><Icon name={icon}/><span>{label}</span></button>)}</nav>}
function ProfileView({userId,profile,wealth,go}:{userId:string;profile:Profile;wealth:Wealth;go:(s:Screen)=>void}){return <section className="f-page profile-new"><PageTitle tag="MON PARCOURS" title={`@${profile.username}`} text={`${profile.financial_archetype??"Profil en construction"} · ${fmt(wealth.total_value)} Koins`}/><div className="profile-cards"><article><span>PHILOSOPHIE</span><h2>La qualité avant le score brut.</h2><p>Ton profil évolue avec tes connaissances, ta calibration, ton risque, ta discipline et ta régularité — pas uniquement avec tes gains.</p></article><button className="profile-network-card" onClick={()=>go("network")}><span>TRANSPARENCY</span><h2>Whale Watch · Blockchain</h2><p>Transactions publiques, sources d’attribution et alertes Premium.</p><i>Ouvrir →</i></button></div><AlertSettings userId={userId} premium={profile.subscription_tier==="premium"}/><PremiumV2/>{profile.role==="admin"&&<button className="admin-entry" onClick={()=>go("admin")}>Ouvrir le centre d’administration →</button>}<button className="logout" onClick={()=>supabase.auth.signOut()}>Se déconnecter</button></section>}
function AlertSettings({userId,premium}:{userId:string;premium:boolean}){const[prefs,setPrefs]=useState({market_move_points:4,asset_move_percent:3,whale_minimum_eur:25000,play_enabled:true,finance_enabled:true,blockchain_enabled:true});const[status,setStatus]=useState("");useEffect(()=>{void supabase.from("notification_preferences").select("market_move_points,asset_move_percent,whale_minimum_eur,play_enabled,finance_enabled,blockchain_enabled").eq("user_id",userId).single().then(({data})=>{if(data)setPrefs({market_move_points:Number(data.market_move_points),asset_move_percent:Number(data.asset_move_percent),whale_minimum_eur:Number(data.whale_minimum_eur),play_enabled:data.play_enabled,finance_enabled:data.finance_enabled,blockchain_enabled:data.blockchain_enabled})})},[userId]);const save=async()=>{const{error}=await supabase.from("notification_preferences").upsert({user_id:userId,...prefs,updated_at:new Date().toISOString()},{onConflict:"user_id"});setStatus(error?error.message:"Préférences d’alertes enregistrées.")};return <section className="alert-settings"><header><div><span>ALERTES</span><h2>Quand Konsens doit me prévenir</h2></div><button onClick={save}>Enregistrer</button></header><div><label>Prédictions · mouvement de probabilité<input type="range" min="1" max="20" step="1" value={prefs.market_move_points} onChange={e=>setPrefs({...prefs,market_move_points:Number(e.target.value)})}/><b>{prefs.market_move_points} pt</b></label><label>Finance · mouvement de cours<input type="range" min="0.5" max="15" step="0.5" value={prefs.asset_move_percent} onChange={e=>setPrefs({...prefs,asset_move_percent:Number(e.target.value)})}/><b>{prefs.asset_move_percent}%</b></label><label className={!premium?"locked":""}>Blockchain · grosse transaction<input disabled={!premium} type="range" min="10000" max="200000" step="5000" value={prefs.whale_minimum_eur} onChange={e=>setPrefs({...prefs,whale_minimum_eur:Number(e.target.value)})}/><b>{premium?`${Math.round(prefs.whale_minimum_eur/1000)}k €`:"Premium"}</b></label></div>{status&&<p>{status}</p>}</section>}
function Admin(){return <section className="f-page"><PageTitle tag="ADMINISTRATION" title="Centre de pilotage" text="Monétisation, fournisseurs, API et génération de marchés."/><div className="admin-grid-links"><a className="admin-link" href="/monetization">Konsens Monetization →</a><a className="admin-link" href="/monetization/ads">Régie publicitaire →</a><a className="admin-link" href="/monetization/providers">Raccordements fournisseurs →</a></div></section>}
function PageTitle({tag,title,text}:{tag:string;title:string;text:string}){return <header className="f-page-title"><span>{tag}</span><h1>{title}</h1><p>{text}</p></header>}
function Auth(){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[mode,setMode]=useState<"signup"|"login">("login"),[status,setStatus]=useState("");const social=async(provider:"google"|"apple")=>{const{error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo:location.origin}});if(error)setStatus(error.message)};const submit=async(e:React.FormEvent)=>{e.preventDefault();setStatus("Connexion…");const result=mode==="signup"?await supabase.auth.signUp({email,password,options:{emailRedirectTo:location.origin}}):await supabase.auth.signInWithPassword({email,password});setStatus(result.error?.message??(mode==="signup"?"Vérifie ta boîte mail pour confirmer ton inscription.":"Connecté."))};return <main className="finance-auth"><section className="auth-pitch"><Brand/><span>1 000 KOINS · ZÉRO ARGENT RÉEL</span><h1>Entraîne tes décisions.<br/><em>Pas seulement ton portefeuille.</em></h1><p>Chaque jour : comprendre, prédire, décider et apprendre dans un environnement sans argent réel.</p><div className="auth-proof"><b>5 min / jour</b><b>Marchés connectés</b><b>Score de décision</b></div></section><section className="auth-panel"><span>BIENVENUE</span><h2>{mode==="login"?"Reprendre mon parcours":"Commencer mon entraînement"}</h2><div className="social"><button onClick={()=>social("apple")}>Continuer avec Apple</button><button onClick={()=>social("google")}>Continuer avec Google</button></div><i>ou</i><form onSubmit={submit}><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Mot de passe<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary">{mode==="login"?"Me connecter":"Créer mon compte"}</button></form>{status&&<p>{status}</p>}<button className="auth-switch" onClick={()=>setMode(mode==="login"?"signup":"login")}>{mode==="login"?"Créer un compte":"J’ai déjà un compte"}</button><small>Les Koins sont une unité virtuelle sans valeur monétaire.</small></section></main>}
function Onboarding({user,done}:{user:User;done:()=>void}){const[today]=useState(()=>Date.now()),[p,setP]=useState({username:"",first_name:"",last_name:"",birth_date:"",email:user.email??""});const age=useMemo(()=>p.birth_date?Math.floor((today-new Date(p.birth_date).getTime())/31557600000):0,[p.birth_date,today]);const save=async()=>{if(age<18)return;const{error}=await supabase.from("profiles").update({...p,onboarding_completed_at:new Date().toISOString(),journey_mode:"balanced"}).eq("id",user.id);if(!error){notify;done()}};return <main className="finance-auth onboarding-new"><section className="auth-pitch"><Brand/><span>TON POINT DE DÉPART</span><h1>1 000 Koins.<br/><em>Des décisions à entraîner.</em></h1><p>Konsens ne te demande pas d’être déjà expert. Il mesure ta progression et t’explique pourquoi tes décisions s’améliorent.</p></section><section className="auth-panel"><span>PROFIL</span><h2>Créons ton identité Konsens</h2><label>Pseudo public<input value={p.username} onChange={e=>setP({...p,username:e.target.value.replace(/[^a-zA-Z0-9_]/g,"")})}/></label><div className="field-pair"><label>Prénom<input value={p.first_name} onChange={e=>setP({...p,first_name:e.target.value})}/></label><label>Nom<input value={p.last_name} onChange={e=>setP({...p,last_name:e.target.value})}/></label></div><label>Date de naissance<input type="date" value={p.birth_date} onChange={e=>setP({...p,birth_date:e.target.value})}/></label>{p.birth_date&&age<18&&<p>Konsens est actuellement réservé aux personnes majeures.</p>}<button className="primary" disabled={p.username.length<3||!p.first_name||!p.last_name||age<18} onClick={save}>Commencer mon premier parcours</button></section></main>}
