"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@supabase/supabase-js";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mxuevsspybxoovsutsbs.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_Xs7hyyDA2XUkbwXGGfSE2w_tARkgSL7");

type Go=(screen:"play"|"invest"|"learn"|"profile"|"network")=>void;
type Score={total_score:number;prediction_score:number;risk_score:number;knowledge_score:number;discipline_score:number;diversification_score:number;calibration_score:number;archetype:string;streak_days:number;best_streak:number};
type Session={understand_completed_at:string|null;predict_completed_at:string|null;decide_completed_at:string|null;learn_completed_at:string|null;completed_at:string|null;xp_earned:number};
type Market={id:string;question:string;category:string;yes_probability:number;source_summary:string|null;ai_confidence:number|null;ai_rationale:string|null;closes_at:string};
type Asset={id:string;symbol:string;name:string;sector:string|null;description:string|null};
type Lesson={id:string;title:string;summary:string;concept:string;duration_minutes:number};
type Replay={id:string;title:string;era:string;setup:string;known_at_time:string[];choices:{label:string;impact:string}[];reveal_text:string;lesson:string;difficulty:string};
type League={id:string;name:string;join_code:string;ranking_dimension:string;member_count:number};
type ProfileCard={username:string;total_score:number;archetype:string;prediction_score:number;risk_score:number;knowledge_score:number;discipline_score:number;streak_days:number;total_wealth:number};
type Journal={id:string;decision_type:string;reason_code:string|null;confidence:number|null;thesis:string|null;credits:number;result_delta:number|null;result_label:string|null;lesson:string|null;decision_at:string};

const emptyScore:Score={total_score:50,prediction_score:50,risk_score:50,knowledge_score:50,discipline_score:50,diversification_score:50,calibration_score:50,archetype:"Explorateur",streak_days:0,best_streak:0};
const stepKeys=["understand","predict","decide","learn"] as const;
type Step=typeof stepKeys[number];

export default function JourneyV3({username,cash,premium,go}:{username:string;cash:number;premium:boolean;go:Go}){
 const[score,setScore]=useState<Score>(emptyScore);const[session,setSession]=useState<Session|null>(null);const[market,setMarket]=useState<Market|null>(null);const[asset,setAsset]=useState<Asset|null>(null);const[lesson,setLesson]=useState<Lesson|null>(null);const[replays,setReplays]=useState<Replay[]>([]);const[leagues,setLeagues]=useState<League[]>([]);const[journal,setJournal]=useState<Journal[]>([]);const[profileCard,setProfileCard]=useState<ProfileCard|null>(null);const[loading,setLoading]=useState(true);const[status,setStatus]=useState("");const[open,setOpen]=useState<Step|null>(null);const[prediction,setPrediction]=useState<"yes"|"no">("yes");const[confidence,setConfidence]=useState(60);const[reason,setReason]=useState("analyse");const[thesis,setThesis]=useState("");const[stake,setStake]=useState(25);const[learnAnswer,setLearnAnswer]=useState<number|null>(null);const[replay,setReplay]=useState<Replay|null>(null);const[replayChoice,setReplayChoice]=useState<number|null>(null);const[leagueName,setLeagueName]=useState("");const[joinCode,setJoinCode]=useState("");const[whatIfAmount,setWhatIfAmount]=useState(100);const[whatIfMonths,setWhatIfMonths]=useState(12);const[busy,setBusy]=useState(false);

 const load=async()=>{setLoading(true);const[s,d,m,a,l,r,lg,j,pc]=await Promise.all([
  supabase.rpc("get_my_konsens_score"),supabase.rpc("ensure_daily_session"),
  supabase.from("markets").select("id,question,category,yes_probability,source_summary,ai_confidence,ai_rationale,closes_at").eq("status","open").order("volume_koins",{ascending:false}).limit(1).maybeSingle(),
  supabase.from("assets").select("id,symbol,name,sector,description").eq("is_active",true).like("external_ref","market:%").order("symbol").limit(1).maybeSingle(),
  supabase.from("learning_modules").select("id,title,summary,concept,duration_minutes").eq("is_active",true).order("position").limit(1).maybeSingle(),
  supabase.from("replay_scenarios").select("id,title,era,setup,known_at_time,choices,reveal_text,lesson,difficulty").eq("active",true).order("position").limit(8),
  supabase.rpc("get_my_leagues"),
  supabase.from("decision_journal").select("id,decision_type,reason_code,confidence,thesis,credits,result_delta,result_label,lesson,decision_at").order("decision_at",{ascending:false}).limit(8),
  supabase.rpc("get_profile_card")
 ]);
 const sr=(Array.isArray(s.data)?s.data[0]:s.data) as any;if(sr)setScore(numericScore(sr));const ds=(Array.isArray(d.data)?d.data[0]:d.data) as any;if(ds)setSession(ds as Session);if(m.data)setMarket({...m.data,yes_probability:Number(m.data.yes_probability),ai_confidence:m.data.ai_confidence==null?null:Number(m.data.ai_confidence)} as Market);if(a.data)setAsset(a.data as Asset);if(l.data)setLesson(l.data as Lesson);setReplays((r.data??[]) as Replay[]);setLeagues(((lg.data??[]) as any[]).map(x=>({...x,member_count:Number(x.member_count)})));setJournal(((j.data??[]) as any[]).map(x=>({...x,credits:Number(x.credits),confidence:x.confidence==null?null:Number(x.confidence),result_delta:x.result_delta==null?null:Number(x.result_delta)})));const pcr=(Array.isArray(pc.data)?pc.data[0]:pc.data) as any;if(pcr)setProfileCard({...pcr,total_score:Number(pcr.total_score),prediction_score:Number(pcr.prediction_score),risk_score:Number(pcr.risk_score),knowledge_score:Number(pcr.knowledge_score),discipline_score:Number(pcr.discipline_score),streak_days:Number(pcr.streak_days),total_wealth:Number(pcr.total_wealth)});setLoading(false)};
 useEffect(()=>{void load()},[]);
 const progress=session?[session.understand_completed_at,session.predict_completed_at,session.decide_completed_at,session.learn_completed_at].filter(Boolean).length:0;
 const next=stepKeys.find(k=>!isDone(session,k))??null;
 const coach=useMemo(()=>coachInsight(score,journal),[score,journal]);

 const complete=async(step:Step,xp=10)=>{const{data,error}=await supabase.rpc("complete_daily_step",{p_step:step,p_xp:xp});if(error){setStatus(error.message);return}const row=Array.isArray(data)?data[0]:data;if(row)setSession(row as Session);const fresh=await supabase.rpc("get_my_konsens_score");const sr=Array.isArray(fresh.data)?fresh.data[0]:fresh.data;if(sr)setScore(numericScore(sr));setOpen(null)};
 const placePrediction=async()=>{if(!market||busy)return;setBusy(true);setStatus("Exécution de ta prédiction…");const{data:auth}=await supabase.auth.getUser();if(!auth.user){setBusy(false);return}const{data,error}=await supabase.from("trade_orders").insert({user_id:auth.user.id,market_id:market.id,asset_id:null,side:"buy",outcome:prediction,credits:stake,idempotency_key:crypto.randomUUID()}).select("id,status,rejection_reason").single();if(error||data?.status!=="executed"){setStatus(error?.message??data?.rejection_reason??"Ordre refusé");setBusy(false);return}await supabase.rpc("save_decision_note",{p_trade_order_id:data.id,p_reason:reason,p_confidence:confidence,p_thesis:thesis||`Je pense que la probabilité réelle est proche de ${confidence}%.`,p_expectation:`Je m'attends à ce que ${prediction.toUpperCase()} se réalise.`,p_emotion:"neutre"});await complete("predict",15);window.dispatchEvent(new Event("konsens:trade"));setStatus("Prédiction enregistrée. Konsens te la fera revoir plus tard.");setBusy(false);await load()};
 const placeInvestment=async()=>{if(!asset||busy)return;setBusy(true);setStatus("Simulation de décision…");const{data:auth}=await supabase.auth.getUser();if(!auth.user){setBusy(false);return}const{data,error}=await supabase.from("trade_orders").insert({user_id:auth.user.id,asset_id:asset.id,market_id:null,side:"buy",outcome:null,credits:stake,idempotency_key:crypto.randomUUID()}).select("id,status,rejection_reason").single();if(error||data?.status!=="executed"){setStatus(error?.message??data?.rejection_reason??"Ordre refusé");setBusy(false);return}await supabase.rpc("save_decision_note",{p_trade_order_id:data.id,p_reason:reason,p_confidence:confidence,p_thesis:thesis||`Je prends une petite position pour tester mon raisonnement.`,p_expectation:"Je veux observer le résultat sans surdimensionner le risque.",p_emotion:"neutre"});await complete("decide",15);window.dispatchEvent(new Event("konsens:trade"));setStatus("Décision enregistrée dans ton journal.");setBusy(false);await load()};
 const validateLearn=async()=>{if(learnAnswer==null)return;await complete("learn",15);setStatus(learnAnswer===1?"Bonne réponse : diversification ≠ absence de risque.":"Réponse enregistrée. La diversification réduit certains risques sans les supprimer.")};
 const playReplay=async()=>{if(!replay||replayChoice==null)return;const{data:auth}=await supabase.auth.getUser();if(!auth.user)return;await supabase.from("replay_sessions").insert({user_id:auth.user.id,scenario_id:replay.id,selected_choice:replayChoice,confidence});setStatus("Replay enregistré : compare maintenant ta décision au résultat historique.")};
 const createLeague=async()=>{if(!leagueName.trim())return;const{error}=await supabase.rpc("create_league",{p_name:leagueName.trim(),p_dimension:"score"});setStatus(error?error.message:"Ligue créée.");setLeagueName("");await load()};
 const joinLeague=async()=>{if(!joinCode.trim())return;const{error}=await supabase.rpc("join_league",{p_code:joinCode.trim()});setStatus(error?"Code de ligue introuvable.":"Ligue rejointe.");setJoinCode("");await load()};
 const saveWhatIf=async()=>{const{data:auth}=await supabase.auth.getUser();if(!auth.user)return;const invested=whatIfAmount*whatIfMonths;const result=Math.round(invested*Math.pow(1.06,whatIfMonths/12));await supabase.from("scenario_simulations").insert({user_id:auth.user.id,title:`DCA ${whatIfAmount} K / mois`,scenario_type:"dca",parameters:{monthly:whatIfAmount,months:whatIfMonths,assumption:0.06},result_summary:{invested,estimated:result}});setStatus("Scénario enregistré dans ton laboratoire.")};
 const shareCard=async()=>{const text=`Konsens Score ${Math.round(score.total_score)}/100 · ${score.archetype} · Prévision ${Math.round(score.prediction_score)} · Risque ${Math.round(score.risk_score)} · Connaissance ${Math.round(score.knowledge_score)}`;if(navigator.share)await navigator.share({title:"Mon profil Konsens",text});else{await navigator.clipboard.writeText(text);setStatus("Carte de profil copiée.")}};

 if(loading)return <section className="journey-v3"><div className="journey-loading">Préparation de ton entraînement du jour…</div></section>;
 return <section className="journey-v3">
  <header className="journey-hero"><div><span>KONSENS · ENTRAÎNEMENT QUOTIDIEN</span><h1>Chaque jour, Konsens entraîne ta capacité à prendre de meilleures décisions avec l’argent.</h1><p>Pas de dashboard à surveiller. Un parcours court pour comprendre un signal, formuler une prédiction, prendre une décision mesurée, puis apprendre du résultat.</p><div className="journey-progress"><div><i style={{width:`${progress/4*100}%`}}/></div><b>{progress}/4</b><span>{session?.completed_at?"Entraînement terminé aujourd’hui":next?`Prochaine étape : ${stepLabel(next)}`:"Parcours prêt"}</span></div></div><ScoreOrb score={score}/></header>

  <section className="daily-konsens"><header><div><span>TON KONSENS DU JOUR · 4 À 7 MIN</span><h2>Bonjour {username}. Fais une chose bien à la fois.</h2></div><b>{session?.xp_earned??0} XP aujourd’hui</b></header><div className="daily-steps"><DailyStep n="01" title="Comprendre" text={market?.source_summary??"Lire un signal avant d’agir."} done={Boolean(session?.understand_completed_at)} active={next==="understand"||open==="understand"} onClick={()=>setOpen("understand")}/><DailyStep n="02" title="Prédire" text={market?.question??"Estimer une probabilité, pas deviner."} done={Boolean(session?.predict_completed_at)} active={next==="predict"||open==="predict"} onClick={()=>setOpen("predict")}/><DailyStep n="03" title="Décider" text={asset?`${asset.symbol} · une décision dimensionnée`:`Investir avec une règle de risque.`} done={Boolean(session?.decide_completed_at)} active={next==="decide"||open==="decide"} onClick={()=>setOpen("decide")}/><DailyStep n="04" title="Apprendre" text={lesson?.title??"Transformer l’erreur en connaissance."} done={Boolean(session?.learn_completed_at)} active={next==="learn"||open==="learn"} onClick={()=>setOpen("learn")}/></div>{open&&<DailyAction step={open} market={market} asset={asset} lesson={lesson} prediction={prediction} setPrediction={setPrediction} confidence={confidence} setConfidence={setConfidence} reason={reason} setReason={setReason} thesis={thesis} setThesis={setThesis} stake={stake} setStake={setStake} cash={cash} learnAnswer={learnAnswer} setLearnAnswer={setLearnAnswer} busy={busy} onUnderstand={()=>complete("understand",10)} onPredict={placePrediction} onDecide={placeInvestment} onLearn={validateLearn}/>}</section>

  <section className="coach-card"><div><span>KONSENS COACH</span><h2>{coach.title}</h2><p>{coach.body}</p><small>{coach.action}</small></div><div className="coach-radar"><Metric label="Prévision" value={score.prediction_score}/><Metric label="Risque" value={score.risk_score}/><Metric label="Savoir" value={score.knowledge_score}/><Metric label="Discipline" value={score.discipline_score}/></div></section>

  <section className="consensus-lab"><header><div><span>LE CONSENSUS</span><h2>Toi contre la foule, le marché et l’IA.</h2></div><button onClick={()=>go("play")}>Voir tous les marchés →</button></header>{market?<div className="consensus-grid"><article><span>COMMUNAUTÉ</span><b>{Math.round(market.yes_probability*100)}%</b><small>probabilité OUI</small></article><article><span>IA À LA CRÉATION</span><b>{Math.round((market.ai_confidence??market.yes_probability)*100)}%</b><small>niveau de confiance</small></article><article><span>TOI</span><b>{confidence}%</b><small>ta conviction actuelle</small></article><aside><strong>{market.question}</strong><p>{market.ai_rationale??"Compare les écarts de conviction avant d’engager des Koins."}</p></aside></div>:<p>Aucun marché disponible.</p>}</section>

  <div className="journey-two"><section className="replay-lab"><header><span>REPLAY DU RÉEL</span><h2>Décide avant de connaître la suite.</h2></header><div className="replay-list">{replays.map(r=><button key={r.id} onClick={()=>{setReplay(r);setReplayChoice(null)}} className={replay?.id===r.id?"active":""}><b>{r.era}</b><span>{r.title}</span></button>)}</div>{replay&&<article className="replay-reader"><p>{replay.setup}</p><div className="known">{replay.known_at_time.map(x=><span key={x}>• {x}</span>)}</div>{replay.choices.map((c,i)=><button key={c.label} className={replayChoice===i?"chosen":""} onClick={()=>setReplayChoice(i)}><b>{c.label}</b><small>{replayChoice===i?c.impact:"Choisir cette décision"}</small></button>)}{replayChoice!=null&&<div className="reveal"><strong>Ce qui s’est passé</strong><p>{replay.reveal_text}</p><small>{replay.lesson}</small><button onClick={playReplay}>Enregistrer mon Replay</button></div>}</article>}</section>
  <section className="whatif-lab"><header><span>ET SI…</span><h2>Teste une stratégie sans risquer un euro.</h2></header><label>Montant mensuel <b>{whatIfAmount} K</b><input type="range" min="25" max="500" step="25" value={whatIfAmount} onChange={e=>setWhatIfAmount(Number(e.target.value))}/></label><label>Durée <b>{whatIfMonths} mois</b><input type="range" min="3" max="60" step="3" value={whatIfMonths} onChange={e=>setWhatIfMonths(Number(e.target.value))}/></label><div className="whatif-result"><span>Avec une hypothèse pédagogique de +6%/an</span><b>{Math.round(whatIfAmount*whatIfMonths*Math.pow(1.06,whatIfMonths/12))} K</b><small>pour {whatIfAmount*whatIfMonths} K versés. Ce n’est pas une prévision.</small></div><button onClick={saveWhatIf}>Enregistrer ce scénario</button></section></div>

  <section className="journal-v3"><header><div><span>JOURNAL DES DÉCISIONS</span><h2>Ce que tu pensais compte autant que le résultat.</h2></div><button onClick={()=>go("invest")}>Prendre une nouvelle décision →</button></header>{journal.length===0?<p>Ton journal se remplira automatiquement après tes prochaines décisions.</p>:<div>{journal.map(j=><article key={j.id}><span>{j.decision_type==="bet"?"PRÉDICTION":"INVESTISSEMENT"}</span><b>{j.thesis||j.reason_code||"Décision enregistrée"}</b><small>Confiance {j.confidence??"—"}% · {Math.round(j.credits)} K · {new Date(j.decision_at).toLocaleDateString("fr-FR")}</small>{j.lesson&&<em>{j.lesson}</em>}</article>)}</div>}</section>

  <section className="league-v3"><header><div><span>LIGUES KONSENS</span><h2>On compare la qualité des décisions, pas seulement la richesse.</h2></div></header><div className="league-actions"><input placeholder="Nom de ma ligue" value={leagueName} onChange={e=>setLeagueName(e.target.value)}/><button onClick={createLeague}>Créer</button><input placeholder="Code d’invitation" value={joinCode} onChange={e=>setJoinCode(e.target.value)}/><button onClick={joinLeague}>Rejoindre</button></div><div className="league-list">{leagues.length===0?<p>Aucune ligue pour le moment. Crée la première avec tes bêta-testeurs.</p>:leagues.map(l=><article key={l.id}><b>{l.name}</b><span>{l.member_count} membre{l.member_count>1?"s":""}</span><code>{l.join_code}</code><small>Classement : Konsens Score</small></article>)}</div></section>

  <section className="profile-card-v3"><div><span>TA CARTE KONSENS</span><h2>{profileCard?.archetype??score.archetype}</h2><p>Une identité financière pédagogique, partageable sans exposer tes données personnelles ni tes positions détaillées.</p><button onClick={shareCard}>Partager ma carte</button></div><article><header><img src="/konsens-logo.png" alt="Konsens"/><b>@{profileCard?.username??username}</b></header><strong>{Math.round(score.total_score)}<small>/100</small></strong><span>KONSENS SCORE</span><div><i>Prévision {Math.round(score.prediction_score)}</i><i>Risque {Math.round(score.risk_score)}</i><i>Savoir {Math.round(score.knowledge_score)}</i></div></article></section>

  <section className="premium-evolution"><div><span>KONSENS PREMIUM</span><h2>{premium?"Ton laboratoire avancé est actif.":"Premium doit t’aider à mieux te comprendre, pas seulement retirer la pub."}</h2><p>Coach approfondi, historique personnel, comparaisons, Whale Watch, alertes intelligentes, scénarios et analyses de progression.</p></div><button onClick={()=>go("profile")}>{premium?"Voir mes outils Premium":"Découvrir Premium · 4,99 €"}</button></section>

  <section className="journey-worlds"><button onClick={()=>go("play")}><b>PLAY</b><span>Explorer tous les marchés</span></button><button onClick={()=>go("invest")}><b>FINANCE</b><span>Travailler ton portefeuille</span></button><button onClick={()=>go("learn")}><b>ACADEMY</b><span>Approfondir un sujet</span></button><button onClick={()=>go("network")}><b>TRANSPARENCY</b><span>Observer la blockchain</span></button></section>{status&&<div className="journey-status">{status}</div>}
 </section>
}

function DailyStep({n,title,text,done,active,onClick}:{n:string;title:string;text:string;done:boolean;active:boolean;onClick:()=>void}){return <button onClick={onClick} className={`daily-step ${done?"done":""} ${active?"active":""}`}><i>{done?"✓":n}</i><div><b>{title}</b><span>{text}</span></div><em>{done?"TERMINÉ":"OUVRIR"}</em></button>}
function DailyAction({step,market,asset,lesson,prediction,setPrediction,confidence,setConfidence,reason,setReason,thesis,setThesis,stake,setStake,cash,learnAnswer,setLearnAnswer,busy,onUnderstand,onPredict,onDecide,onLearn}:{step:Step;market:Market|null;asset:Asset|null;lesson:Lesson|null;prediction:"yes"|"no";setPrediction:(v:"yes"|"no")=>void;confidence:number;setConfidence:(n:number)=>void;reason:string;setReason:(v:string)=>void;thesis:string;setThesis:(v:string)=>void;stake:number;setStake:(n:number)=>void;cash:number;learnAnswer:number|null;setLearnAnswer:(n:number)=>void;busy:boolean;onUnderstand:()=>void;onPredict:()=>void;onDecide:()=>void;onLearn:()=>void}){
 if(step==="understand")return <article className="daily-action understand"><span>1 · COMPRENDRE</span><h3>{market?.category??"Signal du jour"}</h3><p>{market?.source_summary??"Avant toute décision, sépare le fait observable de ton interprétation."}</p><div className="concept-box"><b>Question à retenir</b><p>Qu’est-ce qui est un fait, qu’est-ce qui est une hypothèse, et quelle information pourrait te faire changer d’avis ?</p></div><button onClick={onUnderstand}>J’ai compris · +10 XP</button></article>;
 if(step==="predict")return <article className="daily-action predict"><span>2 · PRÉDIRE</span><h3>{market?.question??"Aucun marché disponible"}</h3><div className="binary"><button className={prediction==="yes"?"active yes":"yes"} onClick={()=>setPrediction("yes")}>OUI</button><button className={prediction==="no"?"active no":"no"} onClick={()=>setPrediction("no")}>NON</button></div><label>Ta confiance <b>{confidence}%</b><input type="range" min="50" max="95" step="5" value={confidence} onChange={e=>setConfidence(Number(e.target.value))}/></label><DecisionFields reason={reason} setReason={setReason} thesis={thesis} setThesis={setThesis}/><Stake stake={stake} setStake={setStake} cash={cash}/><button disabled={busy||!market||cash<stake} onClick={onPredict}>{busy?"Enregistrement…":`Confirmer ${prediction.toUpperCase()} · ${stake} K`}</button></article>;
 if(step==="decide")return <article className="daily-action decide"><span>3 · DÉCIDER</span><h3>{asset?`${asset.name} (${asset.symbol})`:"Actif du jour"}</h3><p>{asset?.description??"Prends une petite décision mesurée, puis observe le résultat."}</p><DecisionFields reason={reason} setReason={setReason} thesis={thesis} setThesis={setThesis}/><label>Confiance dans ton raisonnement <b>{confidence}%</b><input type="range" min="40" max="90" step="5" value={confidence} onChange={e=>setConfidence(Number(e.target.value))}/></label><Stake stake={stake} setStake={setStake} cash={cash}/><button disabled={busy||!asset||cash<stake} onClick={onDecide}>{busy?"Simulation…":`Investir ${stake} K en simulation`}</button></article>;
 return <article className="daily-action learn"><span>4 · APPRENDRE</span><h3>{lesson?.title??"La diversification"}</h3><p>{lesson?.summary??lesson?.concept??"Une bonne décision ne consiste pas à supprimer le risque mais à le rendre supportable."}</p><h4>Une diversification correcte :</h4>{["garantit de ne jamais perdre","répartit les sources de risque sans les supprimer","consiste à acheter le plus d’actifs possible"].map((x,i)=><button key={x} className={learnAnswer===i?"chosen":""} onClick={()=>setLearnAnswer(i)}>{x}</button>)}<button disabled={learnAnswer==null} onClick={onLearn}>Valider ma réponse · +15 XP</button></article>
}
function DecisionFields({reason,setReason,thesis,setThesis}:{reason:string;setReason:(v:string)=>void;thesis:string;setThesis:(v:string)=>void}){return <div className="decision-fields"><label>Pourquoi ?<select value={reason} onChange={e=>setReason(e.target.value)}><option value="analyse">Analyse</option><option value="actualite">Actualité</option><option value="intuition">Intuition</option><option value="strategie">Stratégie long terme</option></select></label><label>Ta thèse en une phrase<input value={thesis} onChange={e=>setThesis(e.target.value)} placeholder="Ce qui me ferait avoir raison…"/></label></div>}
function Stake({stake,setStake,cash}:{stake:number;setStake:(n:number)=>void;cash:number}){return <div className="stake-v3"><span>Mise mesurée · {Math.round(cash)} K disponibles</span>{[10,25,50,100].map(n=><button key={n} className={stake===n?"active":""} onClick={()=>setStake(n)}>{n} K</button>)}</div>}
function ScoreOrb({score}:{score:Score}){return <aside className="score-orb"><span>KONSENS SCORE</span><strong>{Math.round(score.total_score)}</strong><small>/100</small><b>{score.archetype}</b><em>{score.streak_days} j de régularité</em></aside>}
function Metric({label,value}:{label:string;value:number}){return <div><span>{label}</span><b>{Math.round(value)}</b><i style={{width:`${Math.max(4,value)}%`}}/></div>}
function isDone(s:Session|null,k:Step){if(!s)return false;return Boolean(k==="understand"?s.understand_completed_at:k==="predict"?s.predict_completed_at:k==="decide"?s.decide_completed_at:s.learn_completed_at)}
function stepLabel(k:Step){return k==="understand"?"Comprendre":k==="predict"?"Prédire":k==="decide"?"Décider":"Apprendre"}
function numericScore(x:any):Score{return{total_score:Number(x.total_score),prediction_score:Number(x.prediction_score),risk_score:Number(x.risk_score),knowledge_score:Number(x.knowledge_score),discipline_score:Number(x.discipline_score),diversification_score:Number(x.diversification_score),calibration_score:Number(x.calibration_score),archetype:x.archetype??"Explorateur",streak_days:Number(x.streak_days??0),best_streak:Number(x.best_streak??0)}}
function coachInsight(score:Score,journal:Journal[]){const dims=[{k:"prediction",v:score.prediction_score},{k:"risk",v:score.risk_score},{k:"knowledge",v:score.knowledge_score},{k:"discipline",v:score.discipline_score},{k:"diversification",v:score.diversification_score},{k:"calibration",v:score.calibration_score}].sort((a,b)=>a.v-b.v);const weak=dims[0];if(weak.k==="calibration")return{title:"Ta conviction mérite d’être mieux calibrée.",body:"Compare plus souvent ton niveau de confiance au résultat réel. Être bon, ce n’est pas dire 90% souvent : c’est avoir raison environ 9 fois sur 10 quand tu dis 90%.",action:"Aujourd’hui : indique ta confiance avant chaque prédiction."};if(weak.k==="risk")return{title:"Tu peux améliorer le dimensionnement du risque.",body:"Une bonne idée peut devenir une mauvaise décision si la mise est trop grande. Konsens va privilégier de petites positions répétables.",action:"Aujourd’hui : garde chaque nouvelle décision sous 10% de tes Koins disponibles."};if(weak.k==="knowledge")return{title:"Ton prochain levier est la connaissance.",body:"Tes décisions progresseront plus vite si tu renforces les mécanismes derrière les marchés plutôt que de multiplier les paris.",action:"Aujourd’hui : termine le module proposé avant une deuxième décision."};if(journal.length>=3)return{title:"Ton journal devient une vraie source d’apprentissage.",body:`Tu as déjà ${journal.length} décisions récentes documentées. Relis surtout celles où ton niveau de confiance était élevé : ce sont elles qui révèlent le mieux tes biais.`,action:"Aujourd’hui : écris une thèse falsifiable, pas une impression."};return{title:"Construis d’abord une méthode répétable.",body:"Ton score n’a pas vocation à récompenser un coup de chance. Il valorise la qualité du raisonnement, le risque, la connaissance et la régularité.",action:"Termine les 4 étapes du Daily Konsens."}}
