"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient, type User } from "@supabase/supabase-js";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mxuevsspybxoovsutsbs.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_Xs7hyyDA2XUkbwXGGfSE2w_tARkgSL7");
type Screen="home"|"challenges"|"create"|"profile"|"admin";
type Profile={username:string;first_name:string;last_name:string;birth_date:string;email:string;role?:string;onboarding_completed_at?:string|null};

export default function KonsensApp(){
 const [user,setUser]=useState<User|null>(null);const [loading,setLoading]=useState(true);const [profile,setProfile]=useState<Profile|null>(null);const [screen,setScreen]=useState<Screen>("home");const [toast,setToast]=useState("");
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{setUser(data.user);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>{setUser(s?.user??null);setLoading(false)});return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!user)return;supabase.from("profiles").select("username,first_name,last_name,birth_date,email,role,onboarding_completed_at").eq("id",user.id).maybeSingle().then(({data})=>setProfile(data as Profile|null))},[user]);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2400)};
 if(loading)return <main className="blank-state"><span className="brand-mark">K</span><p>Ouverture de Konsens…</p></main>;
 if(!user)return <Auth/>;
 if(!profile?.onboarding_completed_at)return <Onboarding user={user} done={setProfile}/>;
 return <main className="beta-app"><header className="beta-header"><button className="beta-logo" onClick={()=>setScreen("home")}><i>K</i><b>Konsens</b><span>BÊTA</span></button><nav><TopNav active={screen==="home"} label="Accueil" go={()=>setScreen("home")}/><TopNav active={screen==="challenges"} label="Challenges" go={()=>setScreen("challenges")}/><TopNav active={screen==="create"} label="Créer un deal" go={()=>setScreen("create")}/>{profile.role==="admin"&&<TopNav active={screen==="admin"} label="Administration" go={()=>setScreen("admin")}/>}</nav><button className="user-chip" onClick={()=>setScreen("profile")}><i>{profile.username.slice(0,2).toUpperCase()}</i><span><b>@{profile.username}</b><small>0 crédit</small></span></button></header>
  <section className="beta-content">{screen==="home"&&<EmptyHome goCreate={()=>setScreen("create")} goChallenges={()=>setScreen("challenges")}/>} {screen==="challenges"&&<Challenges/>}{screen==="create"&&<CreateDeal done={()=>{notify("Deal envoyé à la modération");setScreen("challenges")}}/>}{screen==="profile"&&<ProfilePage profile={profile}/>} {screen==="admin"&&profile.role==="admin"&&<Admin/>}</section>
  <nav className="beta-mobile"><Mobile label="Accueil" icon="⌂" active={screen==="home"} go={()=>setScreen("home")}/><Mobile label="Challenges" icon="⚡" active={screen==="challenges"} go={()=>setScreen("challenges")}/><Mobile label="Créer" icon="＋" active={screen==="create"} go={()=>setScreen("create")}/><Mobile label="Profil" icon="○" active={screen==="profile"} go={()=>setScreen("profile")}/></nav>{toast&&<div className="k-toast">✓ {toast}</div>}
 </main>
}

function Auth(){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[mode,setMode]=useState<"login"|"signup">("signup");const[status,setStatus]=useState("");
 const social=async(provider:"google"|"apple")=>{const{error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo:location.origin}});if(error)setStatus(error.message)};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setStatus("Connexion…");const result=mode==="signup"?await supabase.auth.signUp({email,password,options:{emailRedirectTo:location.origin}}):await supabase.auth.signInWithPassword({email,password});setStatus(result.error?.message??(mode==="signup"?"Vérifie ta boîte mail pour confirmer ton inscription.":"Connecté."))};
 return <main className="auth-shell"><section className="auth-story"><div className="auth-brand"><i>K</i><b>Konsens</b></div><span>PRÉVOIR · JOUER · COMPRENDRE</span><h1>Et toi,<br/>tu paries sur quoi ?</h1><p>Des challenges inspirés du quotidien et de l’actualité. Des crédits de jeu, jamais d’argent réel.</p><div className="auth-orbit"><i>OUI</i><b>?</b><i>NON</i></div></section><section className="auth-card"><header><span>BIENVENUE</span><h2>{mode==="signup"?"Créer mon compte":"Me connecter"}</h2><p>Simple, rapide et confidentiel.</p></header><div className="social-buttons"><button onClick={()=>social("apple")}><b>●</b> Continuer avec Apple</button><button onClick={()=>social("google")}><b className="google-g">G</b> Continuer avec Google</button></div><div className="or"><span/>ou avec mon adresse mail<span/></div><form onSubmit={submit}><label>Adresse mail<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="toi@exemple.fr"/></label><label>Mot de passe<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="8 caractères minimum"/></label><button className="auth-submit">{mode==="signup"?"Créer mon compte":"Me connecter"} →</button></form>{status&&<p className="auth-status">{status}</p>}<button className="switch-auth" onClick={()=>setMode(mode==="signup"?"login":"signup")}>{mode==="signup"?"J’ai déjà un compte":"Créer un nouveau compte"}</button><small>En continuant, tu confirmes avoir au moins 18 ans et accepter les règles de Konsens.</small></section></main>}

function Onboarding({user,done}:{user:User;done:(p:Profile)=>void}){const[step,setStep]=useState(1);const[today]=useState(()=>Date.now());const[p,setP]=useState<Profile>({username:"",first_name:"",last_name:"",birth_date:"",email:user.email??""});const age=useMemo(()=>p.birth_date?Math.floor((today-new Date(p.birth_date).getTime())/31557600000):0,[p.birth_date,today]);
 const save=async()=>{if(age<18)return;const completed=new Date().toISOString();const{error}=await supabase.from("profiles").update({...p,onboarding_completed_at:completed}).eq("id",user.id);if(!error)done({...p,onboarding_completed_at:completed})};
 return <main className="onboarding"><header><div className="auth-brand"><i>K</i><b>Konsens</b></div><span>ÉTAPE {step}/2</span></header><section><div className="onboard-progress"><i className="done"/><i className={step===2?"done":""}/></div>{step===1?<><span>TON IDENTITÉ KONSENS</span><h1>Comment doit-on<br/>t’appeler ?</h1><p>Seul ton pseudo sera visible par les autres membres.</p><label>Pseudo public<input autoFocus value={p.username} onChange={e=>setP({...p,username:e.target.value.replace(/[^a-zA-Z0-9_]/g,"")})} placeholder="Ex. CyrilProno"/></label><button disabled={p.username.length<3} onClick={()=>setStep(2)}>Continuer →</button></>:<><span>TES INFORMATIONS PRIVÉES</span><h1>Pour sécuriser<br/>ton compte.</h1><p>Ton nom, ton prénom et ta date de naissance ne seront jamais publics.</p><div className="field-pair"><label>Prénom<input value={p.first_name} onChange={e=>setP({...p,first_name:e.target.value})}/></label><label>Nom<input value={p.last_name} onChange={e=>setP({...p,last_name:e.target.value})}/></label></div><label>Date de naissance<input type="date" value={p.birth_date} onChange={e=>setP({...p,birth_date:e.target.value})}/></label>{p.birth_date&&age<18&&<p className="age-error">Konsens est réservé aux personnes majeures.</p>}<label>Adresse mail<input disabled value={p.email}/></label><button disabled={!p.first_name||!p.last_name||age<18} onClick={save}>Entrer dans Konsens →</button></>}</section></main>}

function EmptyHome({goCreate,goChallenges}:{goCreate:()=>void;goChallenges:()=>void}){return <><section className="new-hero"><div><span>BIENVENUE DANS KONSENS</span><h1>Ton instinct.<br/><em>Tes décisions.</em></h1><p>Ton espace est vierge. Les premiers challenges apparaîtront ici dès qu’ils seront publiés et vérifiés.</p><div><button onClick={goChallenges}>Voir les challenges <b>→</b></button><button onClick={goCreate}>Créer mon premier deal</button></div></div><aside><span>MON SOLDE</span><strong>0</strong><b>CRÉDIT</b><p>Ta première dotation sera débloquée après 3 jours d’activité.</p></aside></section><section className="empty-grid"><article><i>⚡</i><div><span>CHALLENGE DU JOUR</span><h2>Aucun challenge publié</h2><p>L’IA prépare les sujets, un administrateur valide les faits et les sources avant publication.</p><button onClick={goChallenges}>Découvrir le fonctionnement</button></div></article><article><i>＋</i><div><span>DEALS DE LA COMMUNAUTÉ</span><h2>À toi d’ouvrir le jeu</h2><p>Pose une question avec deux issues vérifiables et invite la communauté à se positionner.</p><button onClick={goCreate}>Créer un deal</button></div></article></section></>}

function Challenges(){return <section className="empty-page"><header><span>LES PRONOS DU QUOTIDIEN</span><h1>Challenges</h1><p>Les challenges affichés ici seront issus de sources récentes et validés avant ouverture.</p></header><div className="no-data"><i>⚡</i><h2>Aucun challenge ouvert pour le moment</h2><p>La bêta démarre sans contenu fictif. Reviens après la première génération quotidienne.</p><div><span>1</span><p><b>L’IA propose</b><small>Question, réponse et sources</small></p><span>2</span><p><b>L’admin vérifie</b><small>Clarté, date et résolution</small></p><span>3</span><p><b>La communauté joue</b><small>Avec ses crédits sans valeur réelle</small></p></div></div></section>}

function CreateDeal({done}:{done:()=>void}){const[q,setQ]=useState("");const[category,setCategory]=useState("quotidien");const[closes,setCloses]=useState("");const[source,setSource]=useState("");const submit=async(e:React.FormEvent)=>{e.preventDefault();const{error}=await supabase.from("deals").insert({question:q,category,closes_at:new Date(closes).toISOString(),resolution_source_url:source,status:"pending"});if(!error)done()};return <section className="create-page"><header><span>CRÉER UN DEAL</span><h1>Pose ta question.<br/>La communauté tranche.</h1><p>Un bon deal doit être simple, binaire et vérifiable par une source publique.</p></header><form onSubmit={submit}><label>Ta question<input required minLength={15} value={q} onChange={e=>setQ(e.target.value)} placeholder="Ex. Pleuvra-t-il à Paris dimanche ?"/><small>La réponse doit pouvoir être uniquement OUI ou NON.</small></label><div className="field-pair"><label>Catégorie<select value={category} onChange={e=>setCategory(e.target.value)}><option value="quotidien">Quotidien</option><option value="sport">Sport</option><option value="actualite">Actualité</option><option value="finance">Finance</option><option value="culture">Culture</option></select></label><label>Clôture<input required type="datetime-local" value={closes} onChange={e=>setCloses(e.target.value)}/></label></div><label>Source de résolution<input required type="url" value={source} onChange={e=>setSource(e.target.value)} placeholder="https://source-officielle.fr/..."/><small>Cette page permettra de décider objectivement si OUI ou NON gagne.</small></label><div className="deal-preview"><span>APERÇU</span><h2>{q||"Ta question apparaîtra ici"}</h2><div><b>OUI</b><b>NON</b></div></div><button className="deal-submit">Envoyer à la modération →</button></form></section>}

function ProfilePage({profile}:{profile:Profile}){return <section className="profile-page"><div className="profile-avatar">{profile.username.slice(0,2).toUpperCase()}</div><h1>@{profile.username}</h1><p>Compte bêta · 0 crédit</p><div className="private-card"><span>INFORMATIONS CONFIDENTIELLES</span><p><b>Identité</b><strong>{profile.first_name} {profile.last_name}</strong></p><p><b>Adresse mail</b><strong>{profile.email}</strong></p><p><b>Date de naissance</b><strong>{new Date(profile.birth_date).toLocaleDateString("fr-FR")}</strong></p></div><button onClick={()=>supabase.auth.signOut()}>Se déconnecter</button></section>}

function Admin(){const[stats,setStats]=useState({users:0,deals:0,drafts:0});const[users,setUsers]=useState<Profile[]>([]);useEffect(()=>{Promise.all([supabase.from("profiles").select("username,first_name,last_name,birth_date,email,role",{count:"exact"}),supabase.from("deals").select("id",{count:"exact",head:true}).eq("status","pending"),supabase.from("challenge_drafts").select("id",{count:"exact",head:true}).eq("status","pending_review")]).then(([u,d,c])=>{setUsers((u.data??[]) as Profile[]);setStats({users:u.count??0,deals:d.count??0,drafts:c.count??0})})},[]);return <section className="admin-page"><header><div><span>ADMINISTRATION KONSENS</span><h1>Centre de contrôle</h1><p>Données Supabase en temps réel. Aucun compteur de démonstration.</p></div><b>ADMIN</b></header><div className="admin-stats"><article><span>UTILISATEURS</span><strong>{stats.users}</strong><small>Comptes inscrits</small></article><article><span>DEALS À MODÉRER</span><strong>{stats.deals}</strong><small>File de validation</small></article><article><span>CHALLENGES IA</span><strong>{stats.drafts}</strong><small>À vérifier</small></article><article><span>INCIDENTS</span><strong>0</strong><small>Aucun signalement</small></article></div><div className="admin-columns"><article><h2>Actions de maintenance</h2>{["Valider les challenges générés","Modérer les deals membres","Contrôler les sources financières","Consulter les journaux d’erreur"].map(x=><button key={x}>{x}<b>→</b></button>)}</article><article><h2>État des services</h2><p><i className="ok"/>Supabase Auth <b>connecté</b></p><p><i/>Génération IA <b>clé requise</b></p><p><i/>Flux financiers <b>clé requise</b></p><p><i className="ok"/>Application Web <b>opérationnelle</b></p></article></div><section className="admin-users"><h2>Utilisateurs</h2>{users.length===0?<p>Aucun utilisateur inscrit.</p>:users.map(u=><article key={u.username}><i>{u.username.slice(0,2).toUpperCase()}</i><div><b>@{u.username}</b><small>{u.first_name} {u.last_name} · {u.email}</small></div><span>{u.role}</span><button>Gérer</button></article>)}</section></section>}

function TopNav({active,label,go}:{active:boolean;label:string;go:()=>void}){return <button className={active?"active":""} onClick={go}>{label}</button>};function Mobile({active,label,icon,go}:{active:boolean;label:string;icon:string;go:()=>void}){return <button className={active?"active":""} onClick={go}><i>{icon}</i><span>{label}</span></button>}
