"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@supabase/supabase-js";

type Asset={id:string;symbol:string;name:string;kind:string;currency:string;external_ref:string;sector:string|null;description:string|null;instrument_group:string|null;risk_level:string|null;official_url:string|null};
type Point={t:number;price:number;volume?:number};
type Quote={symbol:string;currency:string;exchange:string;price:number;previousClose:number;change:number;changePct:number;updatedAt:string;points:Point[];provider:string};
type Fundamentals={dayHigh:number|null;dayLow:number|null;open:number|null;volume:number|null;averageVolume:number|null;fiftyTwoWeekHigh:number|null;fiftyTwoWeekLow:number|null;marketCap:number|null;trailingPE:number|null;dividendYield:number|null};
type Profile={sector:string|null;description:string|null;instrumentGroup:string|null;riskLevel:string|null;officialUrl:string|null};
type News={title:string;url:string;domain:string;language:string;seenDate:string;sourceCountry:string};
type Position={id:string;asset_id:string;quantity:number;average_price:number};
type QuoteEnvelope={quote?:Quote;fundamentals?:Fundamentals;profile?:Profile;detail?:string;error?:string};
type PortfolioRow={asset:Asset;position:Position;quote?:Quote;value:number;cost:number;pnl:number;pnlPct:number};
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mxuevsspybxoovsutsbs.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_Xs7hyyDA2XUkbwXGGfSE2w_tARkgSL7");
const base=process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mxuevsspybxoovsutsbs.supabase.co";const marketFn=base+"/functions/v1/market-data",newsFn=base+"/functions/v1/finance-news";
const compact=(n:number|null)=>n==null?"—":Intl.NumberFormat("fr-FR",{notation:"compact",maximumFractionDigits:1}).format(n);
function tradeMessage(raw?:string|null){if(!raw)return"Ordre refusé.";if(raw.includes("insufficient_credits"))return"Tu n’as pas assez de Koins disponibles pour cet ordre.";if(raw.includes("insufficient_position"))return"Ta position est trop petite pour revendre ce montant.";if(raw.includes("market_unavailable"))return"Le cours de référence est momentanément indisponible.";if(raw.includes("wallet_missing"))return"Ton portefeuille Konsens n’est pas encore initialisé.";return raw}

export default function LiveFinanceV2({cash,premium}:{cash:number;premium:boolean}){
 const[assets,setAssets]=useState<Asset[]>([]);const[selected,setSelected]=useState<Asset|null>(null);const[quotes,setQuotes]=useState<Record<string,Quote>>({});const[fundamentals,setFundamentals]=useState<Record<string,Fundamentals>>({});const[profiles,setProfiles]=useState<Record<string,Profile>>({});const[news,setNews]=useState<News[]>([]);const[positions,setPositions]=useState<Position[]>([]);const[watched,setWatched]=useState<string[]>([]);const[filter,setFilter]=useState<"all"|"watched">("all");const[range,setRange]=useState("1mo");const[amount,setAmount]=useState(100);const[status,setStatus]=useState("");const[busy,setBusy]=useState(false);
 async function loadQuote(asset:Asset,r:string,show=true){const symbol=asset.external_ref.replace("market:","");try{if(show)setStatus("Actualisation du marché…");const res=await fetch(`${marketFn}?symbol=${encodeURIComponent(symbol)}&range=${r}&interval=${r==="1d"?"15m":"1d"}`);const body=(await res.json()) as QuoteEnvelope;if(!res.ok||!body.quote)throw new Error(body.detail??body.error??"Flux indisponible");setQuotes(q=>({...q,[asset.id]:body.quote!}));if(body.fundamentals)setFundamentals(f=>({...f,[asset.id]:body.fundamentals!}));if(body.profile)setProfiles(p=>({...p,[asset.id]:body.profile!}));if(show)setStatus("");return body.quote}catch(e){if(show)setStatus(e instanceof Error?e.message:"Flux indisponible");return undefined}}
 async function loadNews(asset:Asset){try{const r=await fetch(`${newsFn}?q=${encodeURIComponent(asset.name)}`);const b=await r.json();setNews(r.ok?(b.articles??[]):[])}catch{setNews([])}}
 async function reloadPositions(){const{data:auth}=await supabase.auth.getUser();if(!auth.user)return;const{data:p}=await supabase.from("positions").select("id,asset_id,quantity,average_price").eq("user_id",auth.user.id).not("asset_id","is",null);setPositions(((p??[]) as any[]).map(x=>({...x,quantity:Number(x.quantity),average_price:Number(x.average_price)})))}
 useEffect(()=>{void(async()=>{const{data:auth}=await supabase.auth.getUser();const[a,p,w]=await Promise.all([supabase.from("assets").select("id,symbol,name,kind,currency,external_ref,sector,description,instrument_group,risk_level,official_url").eq("is_active",true).like("external_ref","market:%").order("kind").order("symbol"),auth.user?supabase.from("positions").select("id,asset_id,quantity,average_price").eq("user_id",auth.user.id).not("asset_id","is",null):Promise.resolve({data:[]}),auth.user?supabase.from("asset_watchlist").select("asset_id").eq("user_id",auth.user.id):Promise.resolve({data:[]})]);const rows=(a.data??[]) as Asset[];setAssets(rows);setSelected(x=>x??rows[0]??null);setPositions(((p.data??[]) as any[]).map(x=>({...x,quantity:Number(x.quantity),average_price:Number(x.average_price)})));setWatched(((w.data??[]) as {asset_id:string}[]).map(x=>x.asset_id))})()},[]);
 useEffect(()=>{if(!selected)return;void loadQuote(selected,range);void loadNews(selected)},[selected,range]);
 useEffect(()=>{if(!assets.length)return;void Promise.all(assets.slice(0,10).map(a=>loadQuote(a,"5d",false)))},[assets]);
 const visibleAssets=useMemo(()=>filter==="watched"?assets.filter(a=>watched.includes(a.id)):assets,[assets,watched,filter]);const quote=selected?quotes[selected.id]:undefined;const facts=selected?fundamentals[selected.id]:undefined;const profile=selected?(profiles[selected.id]??{sector:selected.sector,description:selected.description,instrumentGroup:selected.instrument_group,riskLevel:selected.risk_level,officialUrl:selected.official_url}):undefined;const position=selected?positions.find(p=>p.asset_id===selected.id):undefined;const positionValue=position&&quote?position.quantity*quote.price:0;
 const portfolioRows=useMemo<PortfolioRow[]>(()=>positions.map(position=>{const asset=assets.find(a=>a.id===position.asset_id);if(!asset)return null;const q=quotes[asset.id];const cost=position.quantity*position.average_price,value=q?position.quantity*q.price:cost,pnl=value-cost,pnlPct=cost>0?pnl/cost*100:0;return{asset,position,quote:q,value,cost,pnl,pnlPct}}).filter((r):r is PortfolioRow=>Boolean(r)).sort((a,b)=>b.value-a.value),[positions,assets,quotes]);const portfolioValue=portfolioRows.reduce((n,r)=>n+r.value,0),portfolioCost=portfolioRows.reduce((n,r)=>n+r.cost,0),portfolioPnl=portfolioValue-portfolioCost;
 const toggleWatch=async()=>{if(!selected)return;const{data:auth}=await supabase.auth.getUser();if(!auth.user){setStatus("Reconnecte-toi pour gérer tes suivis.");return}const active=watched.includes(selected.id);setWatched(old=>active?old.filter(id=>id!==selected.id):[...old,selected.id]);const result=active?await supabase.from("asset_watchlist").delete().eq("user_id",auth.user.id).eq("asset_id",selected.id):await supabase.from("asset_watchlist").insert({user_id:auth.user.id,asset_id:selected.id});if(result.error){setWatched(old=>active?[...old,selected.id]:old.filter(id=>id!==selected.id));setStatus("Impossible de modifier les suivis.")}else setStatus(active?`${selected.symbol} retiré de tes suivis.`:`${selected.symbol} ajouté à tes suivis · alertes de cours armées.`)};
 const trade=async(side:"buy"|"sell")=>{if(!selected||!quote||busy)return;const{data:auth}=await supabase.auth.getUser();if(!auth.user){setStatus("Reconnecte-toi pour passer un ordre simulé.");return}setBusy(true);await loadQuote(selected,"5d",false);setStatus(side==="buy"?"Achat simulé…":"Revente simulée…");const{data,error}=await supabase.from("trade_orders").insert({user_id:auth.user.id,asset_id:selected.id,market_id:null,side,outcome:null,credits:amount,idempotency_key:crypto.randomUUID()}).select("status,rejection_reason,execution_price").single();if(error||data?.status!=="executed"){setStatus(tradeMessage(data?.rejection_reason??error?.message));setBusy(false);return}const execution=Number(data.execution_price??quote.price);setStatus(side==="buy"?`Achat ${amount} K exécuté à ${execution.toFixed(2)} ${quote.currency||selected.currency}.`:`Revente ${amount} K exécutée à ${execution.toFixed(2)} ${quote.currency||selected.currency}.`);await reloadPositions();window.dispatchEvent(new Event("konsens:trade"));setBusy(false)};
 return <section className="live-finance finance-v2-dense"><header className="live-finance-head"><div><span>KONSENS FINANCE · MARCHÉS CONNECTÉS</span><h1>Observer. Comprendre. Simuler.</h1><p>Cours et historiques externes horodatés, portefeuille personnel, actualités et repères de marché. L’argent reste fictif : tous les ordres utilisent uniquement tes Koins.</p></div><div className="market-live-pill"><i/>FLUX LIVE</div></header>
 <section className="finance-commandbar"><div><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>Tous les marchés</button><button className={filter==="watched"?"active":""} onClick={()=>setFilter("watched")}>★ Mes suivis <b>{watched.length}</b></button></div><aside><span>{assets.length}<small>actifs</small></span><span>{watched.length}<small>alertes suivies</small></span><span>{portfolioRows.length}<small>positions</small></span></aside></section>
 {portfolioRows.length>0&&<section className="finance-portfolio"><header><div><span>MON PORTEFEUILLE</span><h2>Suivre mes investissements</h2></div><div className="finance-portfolio-total"><b>{portfolioValue.toFixed(0)} K</b><small className={portfolioPnl>=0?"positive":"negative"}>{portfolioPnl>=0?"+":""}{portfolioPnl.toFixed(1)} K</small></div></header><div className="finance-position-grid">{portfolioRows.map(row=><button key={row.position.id} onClick={()=>setSelected(row.asset)} className={selected?.id===row.asset.id?"active":""}><div><b>{row.asset.symbol}</b><span>{row.asset.name}</span></div><strong>{row.value.toFixed(0)} K</strong><i className={row.pnl>=0?"positive":"negative"}>{row.pnl>=0?"+":""}{row.pnl.toFixed(1)} K · {row.pnlPct>=0?"+":""}{row.pnlPct.toFixed(2)}%</i><small>PRU {row.position.average_price.toFixed(2)} · {row.position.quantity.toFixed(4)} unités</small></button>)}</div><footer><span>Coût simulé : {portfolioCost.toFixed(0)} K</span><span>Valeur : {portfolioValue.toFixed(0)} K</span><span>P/L : {portfolioPnl>=0?"+":""}{portfolioPnl.toFixed(1)} K</span></footer></section>}
 {filter==="watched"&&visibleAssets.length===0?<div className="finance-empty-watch"><b>☆</b><h3>Aucun marché suivi</h3><p>Ajoute un actif à tes suivis pour le retrouver ici, dans les notifications et le widget.</p><button onClick={()=>setFilter("all")}>Explorer</button></div>:<div className="ticker-rail">{visibleAssets.map(a=>{const q=quotes[a.id];return <button key={a.id} onClick={()=>setSelected(a)} className={selected?.id===a.id?"active":""}><b>{a.symbol}{watched.includes(a.id)?<em>★</em>:null}</b><span>{q?q.price.toFixed(2):"…"}</span><i className={(q?.changePct??0)>=0?"up":"down"}>{q?`${q.changePct>=0?"+":""}${q.changePct.toFixed(2)}%`:"chargement"}</i></button>})}</div>}
 {selected&&<><div className="market-terminal"><aside><div className="finance-asset-kicker"><span>{selected.kind.toUpperCase()}</span><button className={watched.includes(selected.id)?"active":""} onClick={toggleWatch}>{watched.includes(selected.id)?"★ SUIVI":"☆ SUIVRE"}</button></div><h2>{selected.name}</h2><b>{quote?`${quote.price.toFixed(2)} ${quote.currency||selected.currency}`:"—"}</b>{quote&&<i className={quote.changePct>=0?"positive":"negative"}>{quote.changePct>=0?"+":""}{quote.changePct.toFixed(2)}% · {quote.exchange}</i>}<p>{quote?`Dernière donnée : ${new Date(quote.updatedAt).toLocaleString("fr-FR")} · ${quote.provider}`:"Connexion au fournisseur…"}</p><div className="position-box"><span>POSITION KONSENS</span><strong>{position&&quote?`${positionValue.toFixed(0)} Koins`:"Aucune position"}</strong>{position&&<small>{position.quantity.toFixed(4)} unités · PRU {position.average_price.toFixed(2)}</small>}</div></aside><main><div className="chart-toolbar"><div>{["1d","5d","1mo","6mo","1y","5y"].map(r=><button key={r} className={range===r?"active":""} onClick={()=>setRange(r)}>{r.toUpperCase()}</button>)}</div><span>HISTORIQUE DU COURS</span></div><PriceChart points={quote?.points??[]}/></main></div>
 <section className="finance-intel"><article className="asset-profile"><header><span>FICHE ACTIF</span><b className={`risk ${profile?.riskLevel??"medium"}`}>{riskLabel(profile?.riskLevel)}</b></header><h2>{selected.name}</h2><p>{profile?.description??selected.description??"Support de marché utilisé par Konsens pour apprendre à lire un actif avant de simuler une décision."}</p><div><span>{profile?.sector??selected.sector??"Marché"}</span><span>{profile?.instrumentGroup??selected.instrument_group??selected.kind}</span>{profile?.officialUrl&&<a href={profile.officialUrl} target="_blank" rel="noreferrer">Site officiel ↗</a>}</div></article><article className="fundamental-grid"><Metric label="Ouverture" value={facts?.open?.toFixed(2)}/><Metric label="Plus haut jour" value={facts?.dayHigh?.toFixed(2)}/><Metric label="Plus bas jour" value={facts?.dayLow?.toFixed(2)}/><Metric label="Volume" value={compact(facts?.volume??null)}/><Metric label="Moy. volume" value={compact(facts?.averageVolume??null)}/><Metric label="52 sem. haut" value={facts?.fiftyTwoWeekHigh?.toFixed(2)}/><Metric label="52 sem. bas" value={facts?.fiftyTwoWeekLow?.toFixed(2)}/><Metric label="Capitalisation" value={compact(facts?.marketCap??null)}/></article></section>
 <section className="finance-news"><header><div><span>ACTUALITÉ</span><h2>Ce qui peut faire bouger {selected.symbol}</h2></div><small>GDELT · ouvre la source pour vérifier</small></header><div>{news.length===0?<p>Aucune actualité récente remontée pour cet actif.</p>:news.slice(0,6).map((n,i)=><a href={n.url} target="_blank" rel="noreferrer" key={`${n.url}-${i}`}><i>{String(i+1).padStart(2,"0")}</i><div><b>{n.title}</b><span>{n.domain}{n.sourceCountry?` · ${n.sourceCountry}`:""}</span></div><em>↗</em></a>)}</div></section></>}
 <div className="trade-ticket"><div><span>TAILLE DE L’ORDRE · {Math.round(cash)} K disponibles</span>{[25,50,100,250].map(n=><button key={n} className={amount===n?"active":""} onClick={()=>setAmount(n)}>{n} K</button>)}</div><button className="buy" disabled={busy||!quote||cash<amount} onClick={()=>trade("buy")}>{busy?"Ordre en cours…":"Acheter en simulation"}</button><button className="sell" disabled={busy||!quote||positionValue<amount} onClick={()=>trade("sell")}>{busy?"Ordre en cours…":`Revendre ${amount} K`}</button></div>{status&&<p className="market-status">{status}</p>}
 <section className="finance-discipline"><div><span>DISCIPLINE</span><h3>Observer n’est pas investir.</h3></div><p>Les cours sont réels comme référence pédagogique, mais les décisions restent simulées. Une variation passée ne garantit jamais la suivante.</p></section><section className="premium-market"><div><span>KONSENS PREMIUM · 4,99 €/MOIS</span><h2>{premium?"Analyses et transparence enrichies actives":"Passe du cours à l’analyse."}</h2><p>Premium retire la publicité et ouvre notamment les alertes blockchain, les suivis avancés et les futurs fournisseurs premium.</p></div><b>{premium?"PREMIUM ACTIF":"DISPONIBLE DANS PROFIL"}</b></section></section>;
}
function Metric({label,value}:{label:string;value?:string|null}){return <div><span>{label}</span><b>{value??"—"}</b></div>}
function riskLabel(r?:string|null){return r==="very_high"?"RISQUE TRÈS ÉLEVÉ":r==="high"?"RISQUE ÉLEVÉ":r==="low"?"RISQUE FAIBLE":"RISQUE MODÉRÉ"}
function PriceChart({points}:{points:Point[]}){const clean=useMemo(()=>points.filter(p=>Number.isFinite(p.price)).slice(-260),[points]);if(clean.length<2)return <div className="price-chart empty">Historique en cours de chargement…</div>;const min=Math.min(...clean.map(p=>p.price)),max=Math.max(...clean.map(p=>p.price)),span=Math.max(max-min,.0001),path=clean.map((p,i)=>`${i?"L":"M"}${i/(clean.length-1)*800},${230-(p.price-min)/span*190}`).join(" "),positive=clean.at(-1)!.price>=clean[0].price;return <div className={positive?"price-chart positive-chart":"price-chart negative-chart"}><svg viewBox="0 0 800 260" preserveAspectRatio="none"><defs><linearGradient id="fillPrice" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopOpacity=".22"/><stop offset="1" stopOpacity="0"/></linearGradient></defs><path className="area" d={`${path} L800,250 L0,250 Z`}/><path className="line" d={path}/></svg><div className="chart-labels"><span>{clean[0].price.toFixed(2)}</span><b>min {min.toFixed(2)} · max {max.toFixed(2)}</b><span>{clean.at(-1)!.price.toFixed(2)}</span></div></div>}
