"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@supabase/supabase-js";

type Asset={id:string;symbol:string;name:string;kind:string;currency:string;external_ref:string};
type Point={t:number;price:number};
type Quote={symbol:string;currency:string;exchange:string;price:number;previousClose:number;change:number;changePct:number;updatedAt:string;points:Point[];provider:string};
type Position={id:string;asset_id:string;quantity:number;average_price:number};

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mxuevsspybxoovsutsbs.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_Xs7hyyDA2XUkbwXGGfSE2w_tARkgSL7");
const fnBase=(process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mxuevsspybxoovsutsbs.supabase.co")+"/functions/v1/market-data";
const euro=new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:2});

export default function LiveFinanceV2({cash,premium}:{cash:number;premium:boolean}){
 const[assets,setAssets]=useState<Asset[]>([]);const[selected,setSelected]=useState<Asset|null>(null);const[quotes,setQuotes]=useState<Record<string,Quote>>({});const[positions,setPositions]=useState<Position[]>([]);const[range,setRange]=useState("1mo");const[amount,setAmount]=useState(100);const[status,setStatus]=useState("");
 useEffect(()=>{void(async()=>{const {data:auth}=await supabase.auth.getUser();const[a,p]=await Promise.all([supabase.from("assets").select("id,symbol,name,kind,currency,external_ref").eq("is_active",true).like("external_ref","market:%").order("kind").order("symbol"),auth.user?supabase.from("positions").select("id,asset_id,quantity,average_price").eq("user_id",auth.user.id).not("asset_id","is",null):Promise.resolve({data:[]})]);const rows=(a.data??[]) as Asset[];setAssets(rows);setSelected(x=>x??rows[0]??null);setPositions(((p.data??[]) as Array<{id:string;asset_id:string;quantity:number|string;average_price:number|string}>).map(x=>({...x,quantity:Number(x.quantity),average_price:Number(x.average_price)})))})()},[]);
 useEffect(()=>{if(!selected)return;void loadQuote(selected,range)},[selected,range]);
 useEffect(()=>{if(!assets.length)return;void Promise.all(assets.slice(0,10).map(a=>loadQuote(a,"5d",false)))},[assets]);
 const quote=selected?quotes[selected.id]:undefined;const position=selected?positions.find(p=>p.asset_id===selected.id):undefined;const positionValue=position&&quote?position.quantity*quote.price:0;
 const loadQuote=async(asset:Asset,r:string,show=true)=>{const symbol=asset.external_ref.replace("market:","");try{if(show)setStatus("Actualisation du marché…");const res=await fetch(`${fnBase}?symbol=${encodeURIComponent(symbol)}&range=${r}&interval=${r==="1d"?"15m":"1d"}`);const body=await res.json();if(!res.ok||!body.quote)throw new Error(body.detail??body.error??"Flux indisponible");setQuotes(q=>({...q,[asset.id]:body.quote as Quote}));if(show)setStatus("")}catch(e){if(show)setStatus(e instanceof Error?e.message:"Flux indisponible")}};
 const trade=async(side:"buy"|"sell")=>{if(!selected||!quote)return;const {data:auth}=await supabase.auth.getUser();if(!auth.user)return;await loadQuote(selected,"5d",false);setStatus(side==="buy"?"Achat simulé…":"Revente simulée…");const {data,error}=await supabase.from("trade_orders").insert({user_id:auth.user.id,asset_id:selected.id,market_id:null,side,outcome:null,credits:amount,idempotency_key:crypto.randomUUID()}).select("status,rejection_reason").single();if(error||data?.status!=="executed"){setStatus(data?.rejection_reason??error?.message??"Ordre refusé");return}setStatus(side==="buy"?`Achat de ${amount} Koins exécuté au cours réel de référence.`:`Revente de ${amount} Koins exécutée au cours réel de référence.`);const {data:p}=await supabase.from("positions").select("id,asset_id,quantity,average_price").eq("user_id",auth.user.id).not("asset_id","is",null);setPositions(((p??[]) as Array<{id:string;asset_id:string;quantity:number|string;average_price:number|string}>).map(x=>({...x,quantity:Number(x.quantity),average_price:Number(x.average_price)})));window.dispatchEvent(new Event("konsens:trade"))};
 return <section className="live-finance"><header className="live-finance-head"><div><span>PASSERELLE MARCHÉS · BÊTA LIVE</span><h1>Cours réels. Argent fictif.</h1><p>Les Koins simulent l’achat et la revente, mais le prix de référence et l’historique viennent d’un flux de marché externe horodaté. Aucun ordre n’est envoyé à une bourse.</p></div><div className="market-live-pill"><i/>MARCHÉ CONNECTÉ</div></header>
 <div className="ticker-rail">{assets.map(a=>{const q=quotes[a.id];return <button key={a.id} onClick={()=>setSelected(a)} className={selected?.id===a.id?"active":""}><b>{a.symbol}</b><span>{q?q.price.toFixed(2):"…"}</span><i className={(q?.changePct??0)>=0?"up":"down"}>{q?`${q.changePct>=0?"+":""}${q.changePct.toFixed(2)}%`:"chargement"}</i></button>})}</div>
 {selected&&<div className="market-terminal"><aside><span>{selected.kind.toUpperCase()}</span><h2>{selected.name}</h2><b>{quote?`${quote.price.toFixed(2)} ${quote.currency||selected.currency}`:"—"}</b>{quote&&<i className={quote.changePct>=0?"positive":"negative"}>{quote.changePct>=0?"+":""}{quote.changePct.toFixed(2)}% · {quote.exchange}</i>}<p>{quote?`Dernière donnée : ${new Date(quote.updatedAt).toLocaleString("fr-FR")} · ${quote.provider}`:"Connexion au fournisseur…"}</p><div className="position-box"><span>POSITION KONSENS</span><strong>{position&&quote?`${positionValue.toFixed(0)} Koins`:"Aucune position"}</strong>{position&&<small>{position.quantity.toFixed(4)} unités · PRU {position.average_price.toFixed(2)}</small>}</div></aside><main><div className="chart-toolbar"><div>{["1d","5d","1mo","6mo","1y","5y"].map(r=><button key={r} className={range===r?"active":""} onClick={()=>setRange(r)}>{r.toUpperCase()}</button>)}</div><span>HISTORIQUE DU COURS</span></div><PriceChart points={quote?.points??[]}/></main></div>}
 <div className="trade-ticket"><div><span>TAILLE DE L’ORDRE</span>{[25,50,100,250].map(n=><button key={n} className={amount===n?"active":""} onClick={()=>setAmount(n)}>{n} K</button>)}</div><button className="buy" disabled={!quote||cash<amount} onClick={()=>trade("buy")}>Acheter en simulation</button><button className="sell" disabled={!quote||positionValue<amount} onClick={()=>trade("sell")}>Revendre {amount} K</button></div>{status&&<p className="market-status">{status}</p>}
 <section className="premium-market"><div><span>KONSENS PREMIUM · 4,99 €/MOIS</span><h2>{premium?"Flux enrichis actifs":"Passe du cours à l’analyse."}</h2><p>Premium masque les publicités Konsens et ouvre les analyses enrichies, la blockchain publique suivie, les historiques étendus et les futurs fournisseurs premium. Les décisions restent entièrement simulées en Koins.</p></div><b>{premium?"PREMIUM ACTIF":"DÉCOUVRIR PREMIUM"}</b></section>
 </section>
}

function PriceChart({points}:{points:Point[]}){const clean=useMemo(()=>points.filter(p=>Number.isFinite(p.price)).slice(-260),[points]);if(clean.length<2)return <div className="price-chart empty">Historique en cours de chargement…</div>;const min=Math.min(...clean.map(p=>p.price)),max=Math.max(...clean.map(p=>p.price)),span=Math.max(max-min,0.0001);const path=clean.map((p,i)=>`${i?"L":"M"}${(i/(clean.length-1))*800},${230-((p.price-min)/span)*190}`).join(" ");const positive=clean.at(-1)!.price>=clean[0].price;return <div className={positive?"price-chart positive-chart":"price-chart negative-chart"}><svg viewBox="0 0 800 260" preserveAspectRatio="none"><defs><linearGradient id="fillPrice" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopOpacity=".22"/><stop offset="1" stopOpacity="0"/></linearGradient></defs><path className="area" d={`${path} L800,250 L0,250 Z`}/><path className="line" d={path}/></svg><div className="chart-labels"><span>{clean[0].price.toFixed(2)}</span><b>min {min.toFixed(2)} · max {max.toFixed(2)}</b><span>{clean.at(-1)!.price.toFixed(2)}</span></div></div>}
