"use client";

import { useEffect, useState } from "react";
import { createClient } from "@supabase/supabase-js";

type Note={id:string;kind:string;title:string;body:string;payload:Record<string,unknown>;created_at:string;read_at:string|null};
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mxuevsspybxoovsutsbs.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_Xs7hyyDA2XUkbwXGGfSE2w_tARkgSL7");

export default function NotificationCenter({userId,onNavigate}:{userId:string;onNavigate:(route:"play"|"invest"|"profile")=>void}){
 const[notes,setNotes]=useState<Note[]>([]);const[open,setOpen]=useState(false);const[permission,setPermission]=useState<NotificationPermission>(typeof Notification==="undefined"?"default":Notification.permission);const[status,setStatus]=useState("");
 const load=async()=>{const{data}=await supabase.from("notification_events").select("id,kind,title,body,payload,created_at,read_at").eq("user_id",userId).order("created_at",{ascending:false}).limit(40);setNotes((data??[]) as Note[])};
 useEffect(()=>{void load();if("serviceWorker" in navigator)void navigator.serviceWorker.register("/sw.js");const ch=supabase.channel(`konsens-notifications-${userId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"notification_events",filter:`user_id=eq.${userId}`},payload=>{const note=payload.new as Note;setNotes(old=>[note,...old].slice(0,40));void showBrowser(note)}).subscribe();return()=>{void supabase.removeChannel(ch)}},[userId]);
 const showBrowser=async(note:Note)=>{if(typeof Notification==="undefined"||Notification.permission!=="granted")return;const reg=await navigator.serviceWorker?.ready;const route=String(note.payload?.route??"");if(reg)await reg.showNotification(note.title,{body:note.body,icon:"/konsens-logo.png",badge:"/konsens-logo.png",tag:note.id,data:{route}});else new Notification(note.title,{body:note.body,icon:"/konsens-logo.png"})};
 const enable=async()=>{if(typeof Notification==="undefined"){setStatus("Notifications navigateur non disponibles ici.");return}const p=await Notification.requestPermission();setPermission(p);await supabase.from("notification_preferences").upsert({user_id:userId,browser_enabled:p==="granted",updated_at:new Date().toISOString()},{onConflict:"user_id"});setStatus(p==="granted"?"Notifications navigateur activées.":"Autorisation non accordée.")};
 const openNote=async(note:Note)=>{if(!note.read_at){await supabase.from("notification_events").update({read_at:new Date().toISOString()}).eq("id",note.id);setNotes(old=>old.map(n=>n.id===note.id?{...n,read_at:new Date().toISOString()}:n))}const route=String(note.payload?.route??"");if(route==="play")onNavigate("play");else if(route==="finance")onNavigate("invest");else onNavigate("profile");setOpen(false)};
 const unread=notes.filter(n=>!n.read_at).length;
 return <div className="notification-center"><button className="notification-bell" aria-label="Notifications" onClick={()=>setOpen(v=>!v)}><span>◔</span>{unread>0&&<b>{unread>9?"9+":unread}</b>}</button>{open&&<section className="notification-popover"><header><div><span>KONSENS LIVE</span><h3>Notifications</h3></div><button onClick={()=>setOpen(false)}>×</button></header>{permission!=="granted"&&<button className="notification-enable" onClick={enable}>Activer les alertes navigateur</button>}{status&&<small className="notification-status">{status}</small>}<div>{notes.length===0?<p className="notification-empty">Aucune alerte pour le moment. Suis un marché, un actif ou un portefeuille blockchain.</p>:notes.map(n=><button className={n.read_at?"notification-row":"notification-row unread"} key={n.id} onClick={()=>openNote(n)}><i>{n.kind==="asset_move"?"↗":n.kind==="market_move"?"◆":n.kind==="whale_move"?"◈":"•"}</i><span><b>{n.title}</b><small>{n.body}</small><em>{new Date(n.created_at).toLocaleString("fr-FR")}</em></span></button>)}</div><footer>Alertes issues de tes suivis · réglages dans ton profil.</footer></section>}</div>
}
