"use client";

import { useEffect, useState } from "react";
import { createClient } from "@supabase/supabase-js";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mxuevsspybxoovsutsbs.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_Xs7hyyDA2XUkbwXGGfSE2w_tARkgSL7");
type State={subscription_tier:string;status:string;trial_ends_at:string|null};

export default function PremiumV2({compact=false}:{compact?:boolean}){
 const[state,setState]=useState<State>({subscription_tier:"free",status:"none",trial_ends_at:null});const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");
 async function refresh(){const {data:auth}=await supabase.auth.getUser();if(!auth.user)return;const{data}=await supabase.rpc("refresh_my_premium_status");const row=Array.isArray(data)?data[0]:data;if(row)setState(row as State)}
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void refresh()},[]);
 const start=async()=>{setBusy(true);setMsg("Activation…");const{data,error}=await supabase.rpc("start_premium_beta_trial");if(error){setMsg(error.message);setBusy(false);return}const row=Array.isArray(data)?data[0]:data;if(row)setState({subscription_tier:"premium",status:row.status,trial_ends_at:row.trial_ends_at});setMsg("Premium activé : les publicités disparaissent dès le prochain rafraîchissement.");setBusy(false);window.dispatchEvent(new Event("konsens:subscription"));window.setTimeout(()=>location.reload(),800)};
 const active=state.subscription_tier==="premium";
 if(compact)return <section className="premium-v2 compact"><div><span>KONSENS PREMIUM</span><strong>{active?"Premium actif":"14 jours d’essai bêta · puis 4,99 €/mois au lancement"}</strong><p>Sans pub · historiques enrichis · suivi blockchain · analyses avancées · portefeuilles publics.</p></div>{active?<b>ACTIF</b>:<button onClick={start} disabled={busy}>Essayer Premium</button>}</section>;
 return <section className="premium-v2"><header><div><span>KONSENS PREMIUM</span><h1>Moins de bruit. Plus de profondeur.</h1><p>Premium conserve la simulation en Koins mais enrichit l’information : aucune publicité Konsens, données de marché approfondies, blockchain publique et outils d’analyse avancés.</p></div><div className="premium-price"><b>4,99 €</b><span>/ mois</span><small>Bêta : essai gratuit 14 jours, aucun paiement débité</small></div></header><div className="premium-benefits"><article><b>◌</b><h3>Sans publicité</h3><p>Les emplacements sponsorisés sont entièrement masqués pour le compte Premium.</p></article><article><b>⌁</b><h3>Finance enrichie</h3><p>Historique étendu, fournisseurs premium lorsqu’ils sont configurés, contexte et transparence de la donnée.</p></article><article><b>◇</b><h3>Blockchain</h3><p>Suivi de jusqu’à 10 portefeuilles publics, mouvements et accès aux preuves via explorateur.</p></article><article><b>✦</b><h3>Analyse avancée</h3><p>Probabilités, historique des marchés, tendances et futurs outils prédictifs sans modifier la nature éducative de Konsens.</p></article></div><div className="premium-action">{active?<><div><strong>Premium actif</strong><p>{state.status==="trial"&&state.trial_ends_at?`Essai bêta jusqu’au ${new Date(state.trial_ends_at).toLocaleDateString("fr-FR")}.`:"Accès Premium actif."}</p></div><b>✓</b></>:<><div><strong>Tester le parcours Premium maintenant</strong><p>Activation bêta réelle dans ton compte. Aucun moyen de paiement n’est demandé pendant cette phase.</p></div><button onClick={start} disabled={busy}>{busy?"Activation…":"Activer 14 jours gratuitement"}</button></>}{msg&&<small>{msg}</small>}</div><footer>Le paiement Web Stripe et l’abonnement iOS StoreKit sont des adaptateurs séparés : ils seront activés lorsque les identifiants produits/marchands seront configurés. La bêta permet déjà de tester les droits Premium et la suppression des pubs.</footer></section>
}
