"use client";

import { useEffect, useState } from "react";
import { createClient } from "@supabase/supabase-js";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mxuevsspybxoovsutsbs.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_Xs7hyyDA2XUkbwXGGfSE2w_tARkgSL7");
type State={subscription_tier:string;status:string;trial_ends_at:string|null};

export default function PremiumV2({compact=false}:{compact?:boolean}){
 const[state,setState]=useState<State>({subscription_tier:"free",status:"none",trial_ends_at:null});const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");
 async function refresh(){const {data:auth}=await supabase.auth.getUser();if(!auth.user)return;const{data}=await supabase.rpc("refresh_my_premium_status");const row=Array.isArray(data)?data[0]:data;if(row)setState(row as State)}
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void refresh()},[]);
 const start=async()=>{setBusy(true);setMsg("Activation…");const{data,error}=await supabase.rpc("start_premium_beta_trial");if(error){setMsg(error.message);setBusy(false);return}const row=Array.isArray(data)?data[0]:data;if(row)setState({subscription_tier:"premium",status:row.status,trial_ends_at:row.trial_ends_at});setMsg("Premium activé : Coach avancé, Portfolio Lab, alertes blockchain et navigation sans pub sont disponibles.");setBusy(false);window.dispatchEvent(new Event("konsens:subscription"));window.setTimeout(()=>location.reload(),800)};
 const active=state.subscription_tier==="premium";
 if(compact)return <section className="premium-v2 compact"><div><span>KONSENS PREMIUM</span><strong>{active?"Ton intelligence financière augmentée":"14 jours d’essai bêta · puis 4,99 €/mois au lancement"}</strong><p>Coach comportemental avancé · Portfolio Lab sauvegardé · Whale Watch & alertes · sans pub.</p></div>{active?<b>ACTIF</b>:<button onClick={start} disabled={busy}>Essayer Premium</button>}</section>;
 return <section className="premium-v2"><header><div><span>KONSENS PREMIUM</span><h1>Comprendre tes décisions en profondeur.</h1><p>Premium ne vend pas de “meilleures prédictions”. Il donne davantage de recul sur ton comportement : pourquoi tu décides, comment tu calibres ta confiance, où tu concentres le risque et quels scénarios méritent d’être comparés.</p></div><div className="premium-price"><b>4,99 €</b><span>/ mois</span><small>Bêta : essai gratuit 14 jours, aucun paiement débité</small></div></header><div className="premium-benefits"><article><b>✦</b><h3>Coach avancé</h3><p>Analyse des motifs de décision, niveau de confiance, concentration des positions, progrès Academy et habitudes récurrentes.</p></article><article><b>⌁</b><h3>Portfolio Lab</h3><p>Enregistre tes scénarios “Et si…”, compare-les dans le temps et confronte tes intuitions à l’historique réellement disponible.</p></article><article><b>◇</b><h3>Whale Watch</h3><p>Jusqu’à 10 portefeuilles blockchain publics suivis, seuils d’alertes et accès direct aux preuves on-chain.</p></article><article><b>◌</b><h3>Sans publicité</h3><p>Aucun emplacement sponsorisé : l’expérience reste entièrement centrée sur ton parcours d’apprentissage.</p></article></div><div className="premium-action">{active?<><div><strong>Premium actif</strong><p>{state.status==="trial"&&state.trial_ends_at?`Essai bêta jusqu’au ${new Date(state.trial_ends_at).toLocaleDateString("fr-FR")}.`:"Accès Premium actif."}</p></div><b>✓</b></>:<><div><strong>Tester le parcours Premium maintenant</strong><p>Les droits Premium sont réellement appliqués à ton compte bêta. Aucun moyen de paiement n’est demandé aujourd’hui.</p></div><button onClick={start} disabled={busy}>{busy?"Activation…":"Activer 14 jours gratuitement"}</button></>}{msg&&<small>{msg}</small>}</div><footer>Le futur abonnement payant n’augmentera jamais la valeur des Koins et ne donnera aucun avantage mécanique dans les ligues. Stripe Web et StoreKit iOS seront activés séparément lors de la commercialisation.</footer></section>
}
