"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@supabase/supabase-js";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL??"https://mxuevsspybxoovsutsbs.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??"sb_publishable_Xs7hyyDA2XUkbwXGGfSE2w_tARkgSL7");

type Route="play"|"invest"|"learn"|"profile"|"network";
type Step={key:string;type:string;eyebrow:string;title:string;body:string;minutes:number;market_id?:string;asset_id?:string;module_id?:string;symbol?:string;asset_name?:string;community_probability?:number};
type Journey={journey_day:string;title:string;subtitle:string;steps:Step[];completed_steps:string[];answers:Record<string,unknown>;completed_at:string|null};
type Score={total_score:number;knowledge_score:number;calibration_score:number;risk_score:number;discipline_score:number;consistency_score:number;performance_score:number;archetype:string;explanation:Record<string,unknown>};
type Insight={id:string;insight_type:string;priority:number;title:string;body:string;action_label:string|null;action_route:string|null;premium_only:boolean};
type Replay={id:string;slug:string;title:string;era:string;setup:string;known_at_time:string[];choices:{key:string;label:string;score:number}[];reveal_text:string;lesson:string;source_urls:string[];difficulty:string;position:number};
type League={id:string;name:string;join_code:string;description:string;ranking_dimension:string;is_member:boolean;member_count:number};
type Leader={rank:number;user_id:string;username:string;archetype:string;konsens_score:number;knowledge_score:number;risk_score:number;performance_score:number};
type ProfileCard={username:string;archetype:string;konsens_score:number;knowledge_score:number;calibration_score:number;risk_score:number;discipline_score:number;consistency_score:number;performance_score:number;xp:number;streak_days:number;badges:{key:string;label:string}[]};

const dims:[keyof Score,string,string][]=[['knowledge_score','Connaissance','Comprendre'],['calibration_score','Calibration','Prévoir'],['risk_score','Risque','Protéger'],['discipline_score','Discipline','Décider'],['consistency_score','Régularité','Répéter'],['performance_score','Résultat','Mesurer']];

export default function TodayV3({username,premium,wealth,onNavigate}:{username:string;premium:boolean;wealth:number;onNavigate:(route:Route)=>void}){
 const[journey,setJourney]=useState<Journey|null>(null),[score,setScore]=useState<Score|null>(null),[insights,setInsights]=useState<Insight[]>([]),[replays,setReplays]=useState<Replay[]>([]),[leagues,setLeagues]=useState<League[]>([]),[leaders,setLeaders]=useState<Record<string,Leader[]>>({}),[profileCard,setProfileCard]=useState<ProfileCard|null>(null),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[prediction,setPrediction]=useState(55),[decision,setDecision]=useState("observe"),[replayChoice,setReplayChoice]=useState<Record<string,string>>({}),[replayConfidence,setReplayConfidence]=useState<Record<string,number>>({}),[replayResult,setReplayResult]=useState<Record<string,{score:number;reveal_text:string;lesson:string}>>({});
 const load=async()=>{const[j,s,c,r,l,p]=await Promise.all([supabase.rpc("get_my_daily_journey"),supabase.rpc("get_my_konsens_score",{p_persist:true}),supabase.rpc("refresh_my_coach_insights"),supabase.from("replay_scenarios").select("id,slug,title,era,setup,known_at_time,choices,reveal_text,lesson,source_urls,difficulty,position").eq("active",true).order("position"),supabase.rpc("get_discoverable_leagues"),supabase.rpc("get_my_profile_card")]);const jr=Array.isArray(j.data)?j.data[0]:j.data;if(jr)setJourney({...jr,steps:(jr.steps??[]) as Step[]});const sc=Array.isArray(s.data)?s.data[0]:s.data;if(sc)setScore(sc as Score);setInsights((c.data??[]) as Insight[]);setReplays((r.data??[]) as Replay[]);setLeagues(((l.data??[]) as League[]).map(x=>({...x,member_count:Number(x.member_count)})));const pc=Array.isArray(p.data)?p.data[0]:p.data;if(pc)setProfileCard(pc as ProfileCard)};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{for(const league of leagues.filter(l=>l.is_member&&!leaders[l.id]))void loadLeague(league.id)},[leagues]);
 const done=new Set(journey?.completed_steps??[]),progress=journey?.steps.length?Math.round(done.size/journey.steps.length*100):0,nextStep=journey?.steps.find(s=>!done.has(s.key));
 const complete=async(step:Step,answer:Record<string,unknown>={})=>{if(busy)return;setBusy(true);const{error}=await supabase.rpc("complete_daily_step",{p_step_key:step.key,p_answer:answer});if(error)setStatus(error.message);else{setStatus(step.key==="learn"?"Étape enregistrée. Poursuis dans Academy pour approfondir.":"Étape validée · +5 XP");await load()}setBusy(false)};
 const handleStep=async(step:Step)=>{if(step.type==="understand")return complete(step,{acknowledged:true});if(step.type==="predict")return complete(step,{probability:prediction,community_probability:step.community_probability});if(step.type==="decide")return complete(step,{decision,symbol:step.symbol});if(step.type==="learn"){onNavigate("learn");return}}
 const submitReplay=async(replay:Replay)=>{const choice=replayChoice[replay.id];if(!choice){setStatus("Choisis d’abord une décision.");return}setBusy(true);const{data,error}=await supabase.rpc("submit_replay_attempt",{p_scenario_id:replay.id,p_choice_key:choice,p_confidence:replayConfidence[replay.id]??60,p_reflection:null});if(error)setStatus(error.message);else{const row=Array.isArray(data)?data[0]:data;if(row)setReplayResult(old=>({...old,[replay.id]:row}));setStatus("Replay enregistré · ton raisonnement compte dans ta progression.");await load()}setBusy(false)};
 const joinLeague=async(league:League)=>{setBusy(true);const{error}=await supabase.rpc("join_league_by_code",{p_join_code:league.join_code});if(error)setStatus(error.message);else{setStatus(`Tu as rejoint ${league.name}.`);await load()}setBusy(false)};
 async function loadLeague(id:string){const{data}=await supabase.rpc("get_league_leaderboard",{p_league_id:id});setLeaders(old=>({...old,[id]:((data??[]) as Leader[]).map(x=>({...x,rank:Number(x.rank)}))}))}
 const share=async()=>{if(!profileCard)return;const text=`Konsens Score ${profileCard.konsens_score}/100 · ${profileCard.archetype} · Connaissance ${profileCard.knowledge_score} · Risque ${profileCard.risk_score} · Calibration ${profileCard.calibration_score}`;if(navigator.share)await navigator.share({title:"Mon profil Konsens",text});else{await navigator.clipboard.writeText(text);setStatus("Carte de progression copiée.")}};
 return <section className="today-v3">
  <header className="today-intro"><div><span>KONSENS · ENTRAÎNEMENT FINANCIER</span><h1>Chaque jour, entraîne ta capacité à prendre de meilleures décisions avec l’argent.</h1><p>Pas besoin de surveiller un dashboard. Konsens te donne un parcours court : comprendre un fait, formuler une probabilité, prendre une décision fictive et apprendre de ton raisonnement.</p></div><aside><div className="score-orb"><b>{score?.total_score??"—"}</b><span>/100</span></div><strong>{score?.archetype??"Calcul en cours"}</strong><small>Konsens Score</small></aside></header>
  <section className="daily-journey"><header><div><span>AUJOURD’HUI · {journey?.journey_day?new Date(`${journey.journey_day}T12:00:00`).toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long"}):""}</span><h2>{journey?.title??"Ton Konsens du jour"}</h2><p>{journey?.subtitle??"Environ 5 minutes"}</p></div><div className="daily-progress"><b>{progress}%</b><span><i style={{width:`${progress}%`}}/></span><small>{done.size}/{journey?.steps.length??4} étapes</small></div></header><div className="journey-line">{journey?.steps.map((step,index)=><article key={step.key} className={`${done.has(step.key)?"done":""} ${nextStep?.key===step.key?"current":""}`}><div className="step-index">{done.has(step.key)?"✓":String(index+1).padStart(2,"0")}</div><div className="step-copy"><span>{step.eyebrow} · {step.minutes} MIN</span><h3>{step.title}</h3><p>{step.body}</p>{step.type==="predict"&&!done.has(step.key)&&<div className="inline-control"><label>Ta probabilité <b>{prediction}%</b></label><input type="range" min="5" max="95" value={prediction} onChange={e=>setPrediction(Number(e.target.value))}/><small>Consensus actuel : {step.community_probability??"—"}%</small></div>}{step.type==="decide"&&!done.has(step.key)&&<div className="decision-choices">{[['buy','J’investis'],['observe','J’observe'],['avoid','J’évite']].map(([id,label])=><button key={id} onClick={()=>setDecision(id)} className={decision===id?"active":""}>{label}</button>)}</div>}</div><div className="step-action">{done.has(step.key)?<b>FAIT</b>:step.type==="learn"?<button onClick={()=>onNavigate("learn")}>Ouvrir Academy →</button>:<button disabled={busy} onClick={()=>handleStep(step)}>{step.type==="predict"?"Enregistrer ma conviction":step.type==="decide"?"Valider ma décision":"J’ai compris"}</button>}{step.type==="learn"&&!done.has(step.key)&&<button className="secondary" disabled={busy} onClick={()=>complete(step,{studied:true})}>J’ai étudié cette notion</button>}</div></article>)}</div>{journey?.completed_at&&<div className="daily-complete"><b>Parcours du jour terminé.</b><span>Tu as entraîné quatre dimensions différentes. Demain, le contexte changera.</span></div>}</section>
  <section className="score-section"><header><div><span>TON PROFIL DE DÉCISION</span><h2>Le score récompense la qualité, pas le coup de chance.</h2></div><button onClick={share}>Partager ma carte ↗</button></header><div className="score-layout"><article className="score-main"><div className="score-ring" style={{"--score":`${score?.total_score??0}%`} as React.CSSProperties}><strong>{score?.total_score??"—"}</strong><span>KONSENS<br/>SCORE</span></div><div><h3>{score?.archetype}</h3><p>La performance ne représente que 15 % du score. Compréhension, calibration, risque, discipline et régularité comptent davantage.</p><div className="badge-row">{profileCard?.badges?.length?profileCard.badges.map(b=><i key={b.key}>{b.label}</i>):<i>Profil en construction</i>}</div></div></article><div className="score-dimensions">{dims.map(([key,label,verb])=>{const value=Number(score?.[key]??0);return <div key={key}><header><span>{label}<small>{verb}</small></span><b>{value}</b></header><i><em style={{width:`${value}%`}}/></i></div>})}</div></div></section>
  <section className="coach-section"><header><div><span>KONSENS COACH</span><h2>Ce que tes décisions disent de toi.</h2></div><small>{premium?"ANALYSE PREMIUM ACTIVE":"COACH ESSENTIEL"}</small></header><div className="coach-grid">{insights.length?insights.map((insight,index)=><article key={insight.id} className={insight.premium_only?"premium":""}><i>{String(index+1).padStart(2,"0")}</i><span>{insight.premium_only?"PREMIUM · ":""}{insight.insight_type.replaceAll('_',' ')}</span><h3>{insight.title}</h3><p>{insight.body}</p>{insight.action_route&&<button onClick={()=>onNavigate(insight.action_route as Route)}>{insight.action_label??"Agir"} →</button>}</article>):<article><span>PREMIÈRE ANALYSE</span><h3>Prends quelques décisions documentées.</h3><p>Le Coach devient plus précis à mesure qu’il peut comparer tes motifs, ta confiance, tes positions et ta progression Academy.</p></article>}</div></section>
  <section className="replay-section"><header><div><span>REPLAY DU RÉEL</span><h2>Décide avec les informations disponibles à l’époque.</h2></div><p>Pas de hindsight : tu réponds d’abord, Konsens révèle ensuite ce qui s’est passé et ce qu’il fallait apprendre.</p></header><div className="replay-grid">{replays.map(replay=>{const result=replayResult[replay.id];return <article key={replay.id}><div className="replay-era">{replay.era} · {replay.difficulty.toUpperCase()}</div><h3>{replay.title}</h3><p>{replay.setup}</p><ul>{replay.known_at_time.map(x=><li key={x}>{x}</li>)}</ul>{!result?<><div className="replay-choices">{replay.choices.map(choice=><button key={choice.key} className={replayChoice[replay.id]===choice.key?"active":""} onClick={()=>setReplayChoice(old=>({...old,[replay.id]:choice.key}))}>{choice.label}</button>)}</div><label className="replay-confidence">Confiance <b>{replayConfidence[replay.id]??60}%</b><input type="range" min="10" max="95" value={replayConfidence[replay.id]??60} onChange={e=>setReplayConfidence(old=>({...old,[replay.id]:Number(e.target.value)}))}/></label><button className="replay-submit" disabled={busy} onClick={()=>submitReplay(replay)}>Révéler la suite</button></>:<div className="replay-reveal"><b>{result.score}/100</b><p>{result.reveal_text}</p><strong>À retenir</strong><p>{result.lesson}</p>{replay.source_urls.map(url=><a key={url} href={url} target="_blank" rel="noreferrer">Source officielle ↗</a>)}</div>}</article>})}</div></section>
  <section className="league-section"><header><div><span>LIGUES KONSENS</span><h2>Se comparer sur la qualité de décision.</h2></div><p>Le patrimoine seul ne décide pas du classement.</p></header><div className="league-grid">{leagues.map(league=><article key={league.id}><div><span>{league.is_public?"PUBLIQUE":"PRIVÉE"} · {league.member_count} membre{league.member_count>1?"s":""}</span><h3>{league.name}</h3><p>{league.description}</p></div>{league.is_member?<><b className="member-pill">MEMBRE</b><div className="leader-mini">{(leaders[league.id]??[]).slice(0,5).map(row=><div key={row.user_id}><i>#{row.rank}</i><strong>@{row.username}</strong><span>{row.archetype}</span><b>{row.konsens_score}</b></div>)}</div></>:<button disabled={busy} onClick={()=>joinLeague(league)}>Rejoindre →</button>}</article>)}</div></section>
  <section className="path-explore"><header><span>POUR ALLER PLUS LOIN</span><h2>Les trois univers restent là. Le parcours te dit quand les utiliser.</h2></header><div><button onClick={()=>onNavigate("play")}><i>01</i><span>PRÉDIRE</span><b>Konsens Play</b><p>Teste ton jugement sur des événements réels.</p></button><button onClick={()=>onNavigate("invest")}><i>02</i><span>DÉCIDER</span><b>Konsens Finance</b><p>Simule des investissements sur des marchés réels.</p></button><button onClick={()=>onNavigate("learn")}><i>03</i><span>COMPRENDRE</span><b>Konsens Academy</b><p>Transforme une erreur ou une curiosité en connaissance.</p></button></div></section>
  <footer className="today-footer"><img src="/konsens-logo.png" alt="Konsens"/><div><b>Konsens</b><span>Entraîne ton intelligence financière.</span></div><strong>{Math.round(wealth)} K</strong></footer>{status&&<div className="journey-toast">{status}</div>}
 </section>
}
