import WidgetKit
import SwiftUI
import AppIntents

enum WidgetUniverse:String,AppEnum{case play,finance,mixed;static var typeDisplayRepresentation=TypeDisplayRepresentation(name:"Univers Konsens");static var caseDisplayRepresentations:[WidgetUniverse:DisplayRepresentation]=[WidgetUniverse.play:"Jeux",WidgetUniverse.finance:"Finance",WidgetUniverse.mixed:"Jeux + Finance"]}
struct KonsensWidgetIntent:WidgetConfigurationIntent{static var title:LocalizedStringResource="Contenu du widget";static var description=IntentDescription("Choisis les prédictions, les marchés financiers ou les deux.");@Parameter(title:"Afficher",default:WidgetUniverse.mixed)var universe:WidgetUniverse}
struct WidgetMarket:Codable,Hashable{let question:String;let category:String;let probability:Int;let volume:Int;let movement:Double}
struct WidgetAsset:Codable,Hashable{let symbol:String;let name:String;let price:Double;let change:Double;let currency:String}
struct KonsensWidgetEntry:TimelineEntry{let date:Date;let configuration:KonsensWidgetIntent;let wealth:Int;let performance:Double;let markets:[WidgetMarket];let assets:[WidgetAsset]}
struct KonsensWidgetProvider:AppIntentTimelineProvider{
 func placeholder(in context:Context)->KonsensWidgetEntry{.init(date:.now,configuration:KonsensWidgetIntent(),wealth:1000,performance:0,markets:[.init(question:"Bitcoin dépassera-t-il son prochain seuil ?",category:"Crypto",probability:51,volume:0,movement:2.4)],assets:[.init(symbol:"AAPL",name:"Apple",price:221.45,change:1.3,currency:"USD")])}
 func snapshot(for configuration:KonsensWidgetIntent,in context:Context)async->KonsensWidgetEntry{entry(configuration)}
 func timeline(for configuration:KonsensWidgetIntent,in context:Context)async->Timeline<KonsensWidgetEntry>{Timeline(entries:[entry(configuration)],policy:.after(Date().addingTimeInterval(15*60)))}
 private func entry(_ configuration:KonsensWidgetIntent)->KonsensWidgetEntry{let d=UserDefaults(suiteName:"group.com.konsens.beta"),wealth=d?.integer(forKey:"konsens_widget_wealth") ?? 1000,performance=d?.double(forKey:"konsens_widget_performance") ?? 0,md=d?.data(forKey:"konsens_widget_markets"),ad=d?.data(forKey:"konsens_widget_assets"),markets=md.flatMap{try? JSONDecoder().decode([WidgetMarket].self,from:$0)} ?? [],assets=ad.flatMap{try? JSONDecoder().decode([WidgetAsset].self,from:$0)} ?? [];return .init(date:.now,configuration:configuration,wealth:wealth==0 ? 1000:wealth,performance:performance,markets:markets,assets:assets)}
}
struct KonsensWidgetView:View{
 @Environment(\.widgetFamily)private var family;let entry:KonsensWidgetEntry
 private var universe:WidgetUniverse{entry.configuration.universe}
 var body:some View{Group{switch family{case .accessoryCircular:accessoryCircle;case .accessoryRectangular:accessoryRect;case .accessoryInline:accessoryInline;default:standard}}.containerBackground(for:.widget){background}.widgetURL(URL(string:universe == WidgetUniverse.finance ? "konsens://invest":"konsens://play"))}
 private var standard:some View{VStack(alignment:.leading,spacing:9){HStack{mark;VStack(alignment:.leading,spacing:0){Text("KONSENS").font(.system(size:9,weight:.black,design:.rounded)).tracking(1);Text(modeTitle).font(.system(size:7,weight:.bold)).foregroundStyle(.secondary)};Spacer();if universe != WidgetUniverse.play{Text(entry.wealth.formatted()).font(.caption.monospacedDigit().bold());Text("K").font(.system(size:7,weight:.bold)).foregroundStyle(.secondary)}};if family == .systemSmall{smallContent}else{mediumContent};Spacer(minLength:0);HStack{Circle().fill(Color.mint).frame(width:5,height:5);Text("Koins fictifs · 15 min").font(.system(size:6)).foregroundStyle(.secondary);Spacer()}}.padding(3)}
 @ViewBuilder private var smallContent:some View{switch universe{case WidgetUniverse.play:if let m=entry.markets.first{PlayRow(market:m,large:true)}else{empty("Aucun jeu")};case WidgetUniverse.finance:if let a=entry.assets.first{FinanceRow(asset:a,large:true)}else{empty("Marché en attente")};case WidgetUniverse.mixed:if let m=entry.markets.first{PlayRow(market:m,large:false)};if let a=entry.assets.first{FinanceRow(asset:a,large:false)}}}
 @ViewBuilder private var mediumContent:some View{switch universe{case WidgetUniverse.play:HStack(spacing:8){ForEach(Array(entry.markets.prefix(2).enumerated()),id:\.offset){_,m in PlayRow(market:m,large:false)}};case WidgetUniverse.finance:HStack(spacing:8){ForEach(Array(entry.assets.prefix(3).enumerated()),id:\.offset){_,a in FinanceRow(asset:a,large:false)}};case WidgetUniverse.mixed:HStack(spacing:8){if let m=entry.markets.first{PlayRow(market:m,large:false).frame(maxWidth:.infinity)};Rectangle().fill(Color.white.opacity(.08)).frame(width:1);VStack(spacing:6){ForEach(Array(entry.assets.prefix(2).enumerated()),id:\.offset){_,a in FinanceRow(asset:a,large:false)}}.frame(maxWidth:.infinity)}}}
 private var accessoryCircle:some View{ZStack{Image("KonsensLogo").resizable().scaledToFit().clipShape(Circle());if universe == WidgetUniverse.play,let m=entry.markets.first{Text("\(m.probability)%").font(.system(size:10,weight:.black)).padding(3).background(.black.opacity(.7),in:Capsule()).offset(y:18)}}}
 private var accessoryRect:some View{HStack(spacing:7){Image("KonsensLogo").resizable().scaledToFit().frame(width:26,height:26).clipShape(RoundedRectangle(cornerRadius:7));if universe == WidgetUniverse.finance,let a=entry.assets.first{VStack(alignment:.leading){Text(a.symbol).font(.caption.bold());Text(String(format:"%+.1f%%",a.change)).font(.caption2).foregroundStyle(a.change>=0 ? .green:.red)}}else if let m=entry.markets.first{VStack(alignment:.leading){Text(m.category).font(.caption2);Text("OUI \(m.probability)%").font(.caption.bold())}};Spacer()}}
 private var accessoryInline:some View{if universe == WidgetUniverse.finance,let a=entry.assets.first{Text("Konsens · \(a.symbol) \(String(format:"%+.1f%%",a.change))")}else if let m=entry.markets.first{Text("Konsens · \(m.probability)% OUI") }else{Text("Konsens Live")}}
 private var modeTitle:String{switch universe{case WidgetUniverse.play:"PLAY";case WidgetUniverse.finance:"FINANCE";case WidgetUniverse.mixed:"PLAY · FINANCE"}}
 private var mark:some View{Image("KonsensLogo").resizable().scaledToFit().frame(width:31,height:31).clipShape(RoundedRectangle(cornerRadius:9))}
 private var background:some View{ZStack{Color(red:.025,green:.045,blue:.065);if universe != WidgetUniverse.finance{RadialGradient(colors:[Color.purple.opacity(.18),.clear],center:.topTrailing,startRadius:0,endRadius:160)};if universe != WidgetUniverse.play{LinearGradient(colors:[Color.blue.opacity(.05),.clear],startPoint:.bottomLeading,endPoint:.topTrailing)}}}
 private func empty(_ text:String)->some View{Text(text).font(.caption).foregroundStyle(.secondary)}
}
private struct PlayRow:View{let market:WidgetMarket;let large:Bool;var body:some View{VStack(alignment:.leading,spacing:5){HStack{Text(market.category.uppercased()).font(.system(size:6,weight:.bold)).foregroundStyle(.purple);Spacer();Text("\(market.probability)%").font((large ? Font.title2:Font.caption).monospacedDigit().bold()).foregroundStyle(.mint)};Text(market.question).font(.system(size:large ? 11:9,weight:.semibold)).lineLimit(large ? 3:2);HStack{Text("OUI").font(.system(size:6,weight:.black)).foregroundStyle(.mint);Text("x\(String(format:"%.2f",1/max(.02,Double(market.probability)/100)))").font(.system(size:7,weight:.bold)).foregroundStyle(.secondary);if abs(market.movement)>=.05{Text(String(format:"%@%.1f pt",market.movement>0 ? "+":"",market.movement)).font(.system(size:6,weight:.bold)).foregroundStyle(market.movement>=0 ? Color.mint:Color.red)};Spacer();Text("\(market.volume) K").font(.system(size:6)).foregroundStyle(.secondary)}}.padding(8).background(Color.purple.opacity(.07),in:RoundedRectangle(cornerRadius:11))}}
private struct FinanceRow:View{let asset:WidgetAsset;let large:Bool;var body:some View{HStack(alignment:.center,spacing:6){VStack(alignment:.leading,spacing:2){Text(asset.symbol).font(.system(size:large ? 12:9,weight:.black,design:.monospaced));Text(asset.price.formatted(.number.precision(.fractionLength(2)))).font(.system(size:large ? 18:11,weight:.bold,design:.monospaced));Text(asset.currency).font(.system(size:6)).foregroundStyle(.secondary)};Spacer(minLength:2);Text(String(format:"%+.1f%%",asset.change)).font(.system(size:large ? 9:7,weight:.bold)).foregroundStyle(asset.change>=0 ? Color.mint:Color.red)}.padding(8).background(Color.blue.opacity(.055),in:RoundedRectangle(cornerRadius:11))}}
@main struct KonsensWidget:Widget{let kind="KonsensWidget";var body:some WidgetConfiguration{AppIntentConfiguration(kind:kind,intent:KonsensWidgetIntent.self,provider:KonsensWidgetProvider()){entry in KonsensWidgetView(entry:entry)}.configurationDisplayName("Konsens Live").description("Jeux suivis, marchés financiers ou mix des deux.").supportedFamilies([.systemSmall,.systemMedium,.accessoryCircular,.accessoryRectangular,.accessoryInline])}}
