import WidgetKit
import SwiftUI
import AppIntents

enum WidgetUniverse:String,AppEnum{case journey,play,finance,mixed;static var typeDisplayRepresentation=TypeDisplayRepresentation(name:"Univers Konsens");static var caseDisplayRepresentations:[WidgetUniverse:DisplayRepresentation]=[.journey:"Aujourd’hui",.play:"Prédictions",.finance:"Finance",.mixed:"Prédictions + Finance"]}
struct KonsensWidgetIntent:WidgetConfigurationIntent{static var title:LocalizedStringResource="Contenu du widget";static var description=IntentDescription("Choisis ton entraînement du jour, les prédictions, la finance ou un mix.");@Parameter(title:"Afficher",default:WidgetUniverse.journey)var universe:WidgetUniverse}
struct WidgetMarket:Codable,Hashable{let question:String;let category:String;let probability:Int;let volume:Int;let movement:Double}
struct WidgetAsset:Codable,Hashable{let symbol:String;let name:String;let price:Double;let change:Double;let currency:String}
struct KonsensWidgetEntry:TimelineEntry{let date:Date;let configuration:KonsensWidgetIntent;let wealth:Int;let performance:Double;let score:Int;let progress:Int;let next:String;let streak:Int;let archetype:String;let markets:[WidgetMarket];let assets:[WidgetAsset]}
struct KonsensWidgetProvider:AppIntentTimelineProvider{
 func placeholder(in context:Context)->KonsensWidgetEntry{.init(date:.now,configuration:KonsensWidgetIntent(),wealth:1000,performance:0,score:68,progress:2,next:"Décider",streak:4,archetype:"Explorateur",markets:[.init(question:"Bitcoin dépassera-t-il son prochain seuil ?",category:"Crypto",probability:51,volume:0,movement:2.4)],assets:[.init(symbol:"AAPL",name:"Apple",price:221.45,change:1.3,currency:"USD")])}
 func snapshot(for configuration:KonsensWidgetIntent,in context:Context)async->KonsensWidgetEntry{entry(configuration)}
 func timeline(for configuration:KonsensWidgetIntent,in context:Context)async->Timeline<KonsensWidgetEntry>{Timeline(entries:[entry(configuration)],policy:.after(Date().addingTimeInterval(15*60)))}
 private func entry(_ configuration:KonsensWidgetIntent)->KonsensWidgetEntry{let d=UserDefaults(suiteName:"group.com.konsens.beta");let wealth=d?.integer(forKey:"konsens_widget_wealth") ?? 1000;let performance=d?.double(forKey:"konsens_widget_performance") ?? 0;let score=d?.integer(forKey:"konsens_journey_score") ?? 50;let progress=d?.integer(forKey:"konsens_journey_progress") ?? 0;let next=d?.string(forKey:"konsens_journey_next") ?? "Comprendre";let streak=d?.integer(forKey:"konsens_journey_streak") ?? 0;let archetype=d?.string(forKey:"konsens_journey_archetype") ?? "Explorateur";let md=d?.data(forKey:"konsens_widget_markets");let ad=d?.data(forKey:"konsens_widget_assets");let markets=md.flatMap{try? JSONDecoder().decode([WidgetMarket].self,from:$0)} ?? [];let assets=ad.flatMap{try? JSONDecoder().decode([WidgetAsset].self,from:$0)} ?? [];return .init(date:.now,configuration:configuration,wealth:wealth==0 ? 1000:wealth,performance:performance,score:score==0 ? 50:score,progress:progress,next:next,streak:streak,archetype:archetype,markets:markets,assets:assets)}
}
struct KonsensWidgetView:View{
 @Environment(\.widgetFamily)private var family;let entry:KonsensWidgetEntry
 private var universe:WidgetUniverse{entry.configuration.universe}
 var body:some View{Group{switch family{case .accessoryCircular:accessoryCircle;case .accessoryRectangular:accessoryRect;case .accessoryInline:accessoryInline;default:standard}}.containerBackground(for:.widget){background}.widgetURL(URL(string:deepLink))}
 private var standard:some View{VStack(alignment:.leading,spacing:9){HStack{mark;VStack(alignment:.leading,spacing:0){Text("KONSENS").font(.system(size:9,weight:.black,design:.rounded)).tracking(1);Text(modeTitle).font(.system(size:7,weight:.bold)).foregroundStyle(.secondary)};Spacer();if universe == .journey{Text("\(entry.score)").font(.title3.monospacedDigit().bold());Text("/100").font(.system(size:7)).foregroundStyle(.secondary)}else if universe != .play{Text(entry.wealth.formatted()).font(.caption.monospacedDigit().bold());Text("K").font(.system(size:7,weight:.bold)).foregroundStyle(.secondary)}};if family == .systemSmall{smallContent}else{mediumContent};Spacer(minLength:0);HStack{Circle().fill(Color.mint).frame(width:5,height:5);Text(footer).font(.system(size:6)).foregroundStyle(.secondary);Spacer()}}.padding(3)}
 @ViewBuilder private var smallContent:some View{switch universe{case .journey:JourneyRow(entry:entry,compact:false);case .play:if let m=entry.markets.first{PlayRow(market:m,large:true)}else{empty("Aucun marché")};case .finance:if let a=entry.assets.first{FinanceRow(asset:a,large:true)}else{empty("Marché en attente")};case .mixed:if let m=entry.markets.first{PlayRow(market:m,large:false)};if let a=entry.assets.first{FinanceRow(asset:a,large:false)}}}
 @ViewBuilder private var mediumContent:some View{switch universe{case .journey:HStack(spacing:10){JourneyRow(entry:entry,compact:false).frame(maxWidth:.infinity);VStack(alignment:.leading,spacing:7){Text("TON PROFIL").font(.system(size:6,weight:.black)).foregroundStyle(.mint);Text(entry.archetype).font(.caption.bold());Text("\(entry.streak) j de régularité").font(.system(size:7)).foregroundStyle(.secondary);Text("Chaque jour : comprendre, prédire, décider, apprendre.").font(.system(size:7)).foregroundStyle(.secondary).lineLimit(3)}.frame(maxWidth:.infinity)};case .play:HStack(spacing:8){ForEach(Array(entry.markets.prefix(2).enumerated()),id:\.offset){_,m in PlayRow(market:m,large:false)}};case .finance:HStack(spacing:8){ForEach(Array(entry.assets.prefix(3).enumerated()),id:\.offset){_,a in FinanceRow(asset:a,large:false)}};case .mixed:HStack(spacing:8){if let m=entry.markets.first{PlayRow(market:m,large:false).frame(maxWidth:.infinity)};Rectangle().fill(Color.white.opacity(0.08)).frame(width:1);VStack(spacing:6){ForEach(Array(entry.assets.prefix(2).enumerated()),id:\.offset){_,a in FinanceRow(asset:a,large:false)}}.frame(maxWidth:.infinity)}}}
 private var accessoryCircle:some View{ZStack{Circle().stroke(Color.white.opacity(0.14),lineWidth:4);Circle().trim(from:0,to:CGFloat(max(0.04,Double(entry.progress)/4))).stroke(Color.mint,style:StrokeStyle(lineWidth:4,lineCap:.round)).rotationEffect(.degrees(-90));VStack(spacing:-1){Text("\(entry.score)").font(.system(size:13,weight:.black));Text("K").font(.system(size:6,weight:.bold)).foregroundStyle(.secondary)}}}
 private var accessoryRect:some View{HStack(spacing:7){Image("KonsensLogo").resizable().scaledToFit().frame(width:26,height:26).clipShape(RoundedRectangle(cornerRadius:7));if universe == .journey{VStack(alignment:.leading,spacing:1){Text("Score \(entry.score)/100").font(.caption.bold());Text("\(entry.progress)/4 · \(entry.next)").font(.caption2).foregroundStyle(.secondary)}}else if universe == .finance,let a=entry.assets.first{VStack(alignment:.leading){Text(a.symbol).font(.caption.bold());Text(String(format:"%+.1f%%",a.change)).font(.caption2).foregroundStyle(a.change>=0 ? .green:.red)}}else if let m=entry.markets.first{VStack(alignment:.leading){Text(m.category).font(.caption2);Text("OUI \(m.probability)%").font(.caption.bold())}};Spacer()}}
 private var accessoryInline:some View{if universe == .journey{Text("Konsens \(entry.score)/100 · \(entry.next)")}else if universe == .finance,let a=entry.assets.first{Text("Konsens · \(a.symbol) \(String(format:"%+.1f%%",a.change))")}else if let m=entry.markets.first{Text("Konsens · \(m.probability)% OUI")}else{Text("Konsens Live")}}
 private var modeTitle:String{switch universe{case .journey:"AUJOURD’HUI";case .play:"PRÉDIRE";case .finance:"FINANCE";case .mixed:"PLAY · FINANCE"}}
 private var deepLink:String{switch universe{case .journey:"konsens://today";case .play:"konsens://play";case .finance:"konsens://invest";case .mixed:"konsens://play"}}
 private var footer:String{universe == .journey ? "Entraîne ton intelligence financière" : "Koins fictifs · 15 min"}
 private var mark:some View{Image("KonsensLogo").resizable().scaledToFit().frame(width:31,height:31).clipShape(RoundedRectangle(cornerRadius:9))}
 private var background:some View{ZStack{Color(red:0.025,green:0.045,blue:0.065);if universe == .journey{RadialGradient(colors:[Color.mint.opacity(0.12),Color.purple.opacity(0.08),.clear],center:.topTrailing,startRadius:0,endRadius:180)}else{if universe != .finance{RadialGradient(colors:[Color.purple.opacity(0.18),.clear],center:.topTrailing,startRadius:0,endRadius:160)};if universe != .play{LinearGradient(colors:[Color.blue.opacity(0.05),.clear],startPoint:.bottomLeading,endPoint:.topTrailing)}}}}
 private func empty(_ text:String)->some View{Text(text).font(.caption).foregroundStyle(.secondary)}
}
private struct JourneyRow:View{let entry:KonsensWidgetEntry;let compact:Bool;var body:some View{VStack(alignment:.leading,spacing:7){HStack{Text("DAILY KONSENS").font(.system(size:6,weight:.black)).foregroundStyle(.mint);Spacer();Text("\(entry.progress)/4").font(.caption.monospacedDigit().bold())};Text(entry.progress>=4 ? "Entraînement terminé" : "Prochaine étape : \(entry.next)").font(.system(size:compact ? 9:11,weight:.bold)).lineLimit(2);HStack(spacing:3){ForEach(0..<4,id:\.self){index in Capsule().fill(index<entry.progress ? Color.mint:Color.white.opacity(0.08)).frame(height:5)}};Text(entry.archetype).font(.system(size:7)).foregroundStyle(.secondary)}}
private struct PlayRow:View{let market:WidgetMarket;let large:Bool;var body:some View{VStack(alignment:.leading,spacing:5){HStack{Text(market.category.uppercased()).font(.system(size:6,weight:.bold)).foregroundStyle(.purple);Spacer();Text("\(market.probability)%").font((large ? Font.title2:Font.caption).monospacedDigit().bold()).foregroundStyle(.mint)};Text(market.question).font(.system(size:large ? 11:9,weight:.semibold)).lineLimit(large ? 3:2);HStack{Text("OUI").font(.system(size:6,weight:.black)).foregroundStyle(.mint);Text("x\(String(format:"%.2f",1/max(0.02,Double(market.probability)/100)))").font(.system(size:7,weight:.bold)).foregroundStyle(.secondary);Spacer();Text("\(market.volume) K").font(.system(size:6)).foregroundStyle(.secondary)}}.padding(8).background(Color.purple.opacity(0.07),in:RoundedRectangle(cornerRadius:11))}}
private struct FinanceRow:View{let asset:WidgetAsset;let large:Bool;var body:some View{HStack(alignment:.center,spacing:6){VStack(alignment:.leading,spacing:2){Text(asset.symbol).font(.system(size:large ? 12:9,weight:.black,design:.monospaced));Text(asset.price.formatted(.number.precision(.fractionLength(2)))).font(.system(size:large ? 18:11,weight:.bold,design:.monospaced));Text(asset.currency).font(.system(size:6)).foregroundStyle(.secondary)};Spacer(minLength:2);Text(String(format:"%+.1f%%",asset.change)).font(.system(size:large ? 9:7,weight:.bold)).foregroundStyle(asset.change>=0 ? Color.mint:Color.red)}.padding(8).background(Color.blue.opacity(0.055),in:RoundedRectangle(cornerRadius:11))}}
@main struct KonsensWidget:Widget{let kind="KonsensWidget";var body:some WidgetConfiguration{AppIntentConfiguration(kind:kind,intent:KonsensWidgetIntent.self,provider:KonsensWidgetProvider()){entry in KonsensWidgetView(entry:entry)}.configurationDisplayName("Konsens Daily").description("Ton entraînement quotidien, ton Score, tes prédictions ou les marchés suivis.").supportedFamilies([.systemSmall,.systemMedium,.accessoryCircular,.accessoryRectangular,.accessoryInline])}}
