-- Konsens V2: durable educational profiles for the connected finance universe.
alter table public.assets add column if not exists sector text;
alter table public.assets add column if not exists description text;
alter table public.assets add column if not exists instrument_group text;
alter table public.assets add column if not exists risk_level text check(risk_level is null or risk_level in('low','medium','high','very_high'));
alter table public.assets add column if not exists official_url text;
update public.assets set sector='Technologie',instrument_group='Action',risk_level='medium',official_url='https://www.apple.com',description='Apple conçoit et commercialise des appareils, logiciels et services numériques. Dans Konsens, le cours sert uniquement de référence à une simulation en Koins.' where symbol='AAPL';
update public.assets set sector='Aéronautique & défense',instrument_group='Action',risk_level='medium',official_url='https://www.airbus.com',description='Airbus est un groupe aéronautique européen. Son titre est coté à Paris ; Konsens l’utilise comme support pédagogique de simulation.' where symbol='AIR';
update public.assets set sector='Crypto-actif',instrument_group='Crypto',risk_level='very_high',official_url='https://bitcoin.org',description='Bitcoin est un actif numérique décentralisé à offre programmée. Sa forte volatilité en fait un support à risque très élevé.' where symbol='BTC';
update public.assets set sector='Blockchain',instrument_group='Crypto',risk_level='very_high',official_url='https://ethereum.org',description='Ether est l’actif natif du réseau Ethereum. Il sert notamment aux frais réseau et à la sécurisation du protocole.' where symbol='ETH';
update public.assets set sector='Luxe',instrument_group='Action',risk_level='medium',official_url='https://www.lvmh.com',description='LVMH regroupe des maisons internationales du luxe. Le titre est coté à Paris et reste sensible à la consommation mondiale et aux devises.' where symbol='MC';
update public.assets set sector='Technologie',instrument_group='Action',risk_level='medium',official_url='https://www.microsoft.com',description='Microsoft développe logiciels, cloud et services d’intelligence artificielle. Le titre sert ici de support de simulation.' where symbol='MSFT';
update public.assets set sector='Semi-conducteurs',instrument_group='Action',risk_level='high',official_url='https://www.nvidia.com',description='NVIDIA conçoit des processeurs graphiques et plateformes de calcul accéléré. Le titre peut être très sensible aux anticipations de croissance.' where symbol='NVDA';
update public.assets set sector='ETF Nasdaq-100',instrument_group='ETF',risk_level='medium',official_url='https://www.invesco.com/qqq-etf/',description='QQQ réplique principalement le Nasdaq-100. Un ETF diversifie davantage qu’une action unique, sans supprimer le risque de marché.' where symbol='QQQ';
update public.assets set sector='ETF S&P 500',instrument_group='ETF',risk_level='medium',official_url='https://www.ssga.com/us/en/intermediary/etfs/funds/spdr-sp-500-etf-trust-spy',description='SPY cherche à répliquer le S&P 500. Il donne une exposition large aux grandes capitalisations américaines.' where symbol='SPY';
update public.assets set sector='Énergie',instrument_group='Action',risk_level='medium',official_url='https://totalenergies.com',description='TotalEnergies est un groupe multi-énergies. Son cours peut être sensible aux prix de l’énergie, aux marges de raffinage et à la transition énergétique.' where symbol='TTE';
