-- Konsens V2: real public Ethereum registry. Demo wallets are kept for history but disabled.
alter table public.public_wallets add column if not exists wallet_kind text not null default 'pseudonymous' check(wallet_kind in('exchange','protocol','bridge','institution','pseudonymous'));
alter table public.public_wallets add column if not exists native_symbol text;
alter table public.public_wallets add column if not exists observable_balance_native numeric(38,12);
alter table public.public_wallets add column if not exists rank_hint integer;
alter table public.public_wallets add column if not exists source_updated_at timestamptz;
update public.public_wallets set is_active=false where chain like '%-demo' or display_name ilike '%démo%';
insert into public.public_wallets(chain,address,display_name,country_code,attribution_type,confidence_score,attribution_source_url,observable_value_eur,is_active,wallet_kind,native_symbol,rank_hint,source_updated_at) values
('ethereum','0x00000000219ab540356cbb839cbe05303d7705fa','Ethereum Beacon Deposit Contract',null,'publicly_attributed',100,'https://etherscan.io/address/0x00000000219ab540356cbb839cbe05303d7705fa',null,true,'protocol','ETH',1,now()),
('ethereum','0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2','Wrapped Ether (WETH)',null,'publicly_attributed',100,'https://etherscan.io/address/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2',null,true,'protocol','ETH',2,now()),
('ethereum','0xbe0eb53f46cd790cd13851d5eff43d12404d33e8','Binance 7',null,'publicly_attributed',95,'https://etherscan.io/address/0xbe0eb53f46cd790cd13851d5eff43d12404d33e8',null,true,'exchange','ETH',3,now()),
('ethereum','0x40b38765696e3d5d8d9d834d8aad4bb6e418e489','Robinhood',null,'publicly_attributed',95,'https://etherscan.io/address/0x40b38765696e3d5d8d9d834d8aad4bb6e418e489',null,true,'institution','ETH',4,now()),
('ethereum','0x0e58e8993100f1cbe45376c410f97f4893d9bfcd','Upbit 41',null,'publicly_attributed',95,'https://etherscan.io/address/0x0e58e8993100f1cbe45376c410f97f4893d9bfcd',null,true,'exchange','ETH',5,now()),
('ethereum','0x8315177ab297ba92a06054ce80a67ed4dbd7ed3a','Arbitrum Bridge',null,'publicly_attributed',100,'https://etherscan.io/address/0x8315177ab297ba92a06054ce80a67ed4dbd7ed3a',null,true,'bridge','ETH',6,now())
on conflict(chain,address) do update set display_name=excluded.display_name,attribution_type=excluded.attribution_type,confidence_score=excluded.confidence_score,attribution_source_url=excluded.attribution_source_url,is_active=true,wallet_kind=excluded.wallet_kind,native_symbol=excluded.native_symbol,rank_hint=excluded.rank_hint,source_updated_at=excluded.source_updated_at;
drop function if exists public.get_whale_leaderboard(integer);
create function public.get_whale_leaderboard(p_limit integer default 25) returns table(id uuid,chain text,address text,display_name text,wallet_kind text,attribution_type text,confidence_score smallint,attribution_source_url text,native_symbol text,observable_balance_native numeric,observable_value_eur numeric,rank_hint integer,volume_30d_eur numeric,transactions_30d bigint,last_activity timestamptz,source_updated_at timestamptz) language sql stable security definer set search_path=public as $$select w.id,w.chain,w.address,w.display_name,w.wallet_kind,w.attribution_type,w.confidence_score,w.attribution_source_url,w.native_symbol,w.observable_balance_native,w.observable_value_eur,w.rank_hint,coalesce(sum(abs(e.estimated_value_eur)) filter(where e.block_time>=now()-interval '30 days'),0)::numeric,count(e.id) filter(where e.block_time>=now()-interval '30 days')::bigint,max(e.block_time),w.source_updated_at from public.public_wallets w left join public.wallet_events e on e.wallet_id=w.id where w.is_active=true group by w.id,w.chain,w.address,w.display_name,w.wallet_kind,w.attribution_type,w.confidence_score,w.attribution_source_url,w.native_symbol,w.observable_balance_native,w.observable_value_eur,w.rank_hint,w.source_updated_at order by coalesce(w.rank_hint,2147483647),coalesce(w.observable_value_eur,0) desc,13 desc limit greatest(1,least(coalesce(p_limit,25),50))$$;
grant execute on function public.get_whale_leaderboard(integer) to authenticated;
