import SwiftUI

struct ProfileView: View {
    @EnvironmentObject private var store: AppStore
    @ObservedObject private var notifications = NotificationManager.shared
    @State private var showNetwork = false
    @State private var score: KonsensScore?

    var body: some View {
        ScrollView {
            VStack(alignment:.leading,spacing:14) {
                HStack(spacing:15){Image("KonsensLogo").resizable().scaledToFit().frame(width:62,height:62).clipShape(RoundedRectangle(cornerRadius:18,style:.continuous)).overlay(RoundedRectangle(cornerRadius:18).stroke(Color.white.opacity(0.08)));VStack(alignment:.leading,spacing:4){Eyebrow(text:store.subscriptionTier=="premium" ? "KONSENS PREMIUM":"MON PARCOURS");Text("@\(store.username)").font(.title.bold());Text(score?.archetype ?? "Profil de décision en construction").font(.caption).foregroundStyle(Color.konsensMuted)}}
                if let score { DecisionIdentityCard(score:score, username:store.username) }
                Button{store.selectedTab = .wealth}label:{HStack(spacing:13){Image(systemName:"calendar.circle.fill").font(.title3).foregroundStyle(Color.konsensGreen).frame(width:44,height:44).background(Color.konsensGreen.opacity(0.1),in:RoundedRectangle(cornerRadius:13));VStack(alignment:.leading,spacing:4){Eyebrow(text:"AUJOURD’HUI");Text("Reprendre mon entraînement").font(.headline);Text("Comprendre → prédire → décider → apprendre.").font(.system(size:9)).foregroundStyle(Color.konsensMuted)};Spacer();Image(systemName:"chevron.right").foregroundStyle(Color.konsensGreen)}.panel()}.buttonStyle(.plain)
                PremiumProfileCard()
                Button{showNetwork=true}label:{HStack(spacing:13){Image(systemName:"link.circle.fill").font(.title3).foregroundStyle(Color.konsensViolet).frame(width:44,height:44).background(Color.konsensViolet.opacity(0.1),in:RoundedRectangle(cornerRadius:13));VStack(alignment:.leading,spacing:4){Eyebrow(text:"KONSENS TRANSPARENCY");Text("Whale Watch · Blockchain").font(.headline);Text("Adresses publiques vérifiables, transactions et alertes blockchain Premium.").font(.system(size:9)).foregroundStyle(Color.konsensMuted)};Spacer();Image(systemName:"chevron.right").foregroundStyle(Color.konsensViolet)}.panel()}.buttonStyle(.plain)
                NotificationProfileCard()
                VStack(alignment:.leading,spacing:10){Eyebrow(text:"SÉCURITÉ");Label("Face ID protège ton parcours et tes décisions",systemImage:"faceid").font(.subheadline.bold());Text("La biométrie reste sur ton appareil. Konsens ne reçoit aucune donnée biométrique.").font(.caption).foregroundStyle(Color.konsensMuted)}.panel()
                VStack(alignment:.leading,spacing:8){Eyebrow(text:"REPÈRE");HStack{ProfileStat(value:store.wealth.total.formatted(.number.precision(.fractionLength(0))),label:"Koins totaux");ProfileStat(value:String(format:"%+.1f%%",store.wealth.performance),label:"Performance")};Text("Les Koins restent un terrain d’entraînement. Ton Konsens Score est le repère principal de progression.").font(.system(size:8)).foregroundStyle(Color.konsensMuted)}.panel()
                Button(role:.destructive){Task{await store.signOut()}}label:{Label("Se déconnecter",systemImage:"rectangle.portrait.and.arrow.right").frame(maxWidth:.infinity).padding(14)}.buttonStyle(.plain).foregroundStyle(Color.konsensNegative).background(Color.konsensNegative.opacity(0.08),in:RoundedRectangle(cornerRadius:15))
            }.padding(.horizontal,18).padding(.top,92).padding(.bottom,110)
        }.sheet(isPresented:$showNetwork){NetworkView().environmentObject(store)}.task{await loadScore()}
    }
    private func loadScore() async { struct Params:Encodable{let p_persist:Bool};let rows:[KonsensScore]=(try? await store.supabase.rpc("get_my_konsens_score",params:Params(p_persist:false)).execute().value) ?? [];score=rows.first }
}

private struct DecisionIdentityCard:View{
    let score:KonsensScore;let username:String
    var body:some View{VStack(alignment:.leading,spacing:13){HStack(alignment:.center){VStack(alignment:.leading,spacing:3){Eyebrow(text:"KONSENS SCORE");Text("\(score.total_score)/100").font(.system(size:36,weight:.black,design:.rounded)).foregroundStyle(Color.konsensGreen);Text(score.archetype).font(.headline)};Spacer();ShareLink(item:"Konsens · @\(username) · Score \(score.total_score)/100 · \(score.archetype) · Connaissance \(score.knowledge_score) · Calibration \(score.calibration_score) · Risque \(score.risk_score)"){Image(systemName:"square.and.arrow.up").frame(width:38,height:38).background(Color.white.opacity(0.04),in:Circle())}.buttonStyle(.plain)};LazyVGrid(columns:[GridItem(.flexible()),GridItem(.flexible())],spacing:7){DecisionMetric(title:"Connaissance",value:score.knowledge_score);DecisionMetric(title:"Calibration",value:score.calibration_score);DecisionMetric(title:"Risque",value:score.risk_score);DecisionMetric(title:"Discipline",value:score.discipline_score);DecisionMetric(title:"Régularité",value:score.consistency_score);DecisionMetric(title:"Résultat",value:score.performance_score)};Text("Le patrimoine n’est plus la note finale : Konsens récompense la qualité du raisonnement et la progression.").font(.system(size:8)).foregroundStyle(Color.konsensMuted)}.panel()}
}
private struct DecisionMetric:View{let title:String;let value:Int;var body:some View{VStack(alignment:.leading,spacing:3){Text(title.uppercased()).font(.system(size:6,weight:.black)).foregroundStyle(Color.konsensMuted);Text("\(value)").font(.headline.monospacedDigit().bold())}.frame(maxWidth:.infinity,alignment:.leading).padding(9).background(Color.white.opacity(0.03),in:RoundedRectangle(cornerRadius:10))}}

private struct NotificationProfileCard: View {
    @EnvironmentObject private var store: AppStore
    @ObservedObject private var notifications = NotificationManager.shared
    var body: some View {
        VStack(alignment:.leading,spacing:12){HStack{VStack(alignment:.leading,spacing:3){Eyebrow(text:"KONSENS LIVE");Text("Alertes & notifications").font(.headline)};Spacer();Text("\(notifications.unreadCount)").font(.headline.monospacedDigit()).foregroundStyle(Color.konsensViolet)}
            Text("Cours suivis, mouvements de probabilités, actifs et grosses transactions blockchain Premium.").font(.caption).foregroundStyle(Color.konsensMuted)
            if notifications.authorization != .authorized { Button{Task{await notifications.requestPermission(store:store)}}label:{Label("Activer les notifications iOS",systemImage:"bell.badge.fill").font(.subheadline.bold()).frame(maxWidth:.infinity).padding(11)}.buttonStyle(.plain).foregroundStyle(Color.konsensBackground).background(Color.konsensGreen,in:RoundedRectangle(cornerRadius:13)) }
            ForEach(notifications.events.prefix(5)){event in Button{Task{await notifications.markRead(event,store:store)}}label:{HStack(spacing:9){Image(systemName:event.kind=="asset_move" ? "chart.line.uptrend.xyaxis":event.kind=="market_move" ? "waveform.path.ecg":"link").foregroundStyle(event.kind=="whale_move" ? Color.konsensViolet:Color.konsensBlue).frame(width:28);VStack(alignment:.leading,spacing:2){Text(event.title).font(.caption.bold());Text(event.body).font(.system(size:8)).foregroundStyle(Color.konsensMuted).lineLimit(2)};Spacer();if event.read_at==nil{Circle().fill(Color.konsensViolet).frame(width:6,height:6)}}.padding(9).background(Color.white.opacity(event.read_at==nil ? 0.045:0.02),in:RoundedRectangle(cornerRadius:11))}.buttonStyle(.plain) }
            Text("Les alertes locales sont synchronisées pendant la bêta. Les push hors application nécessitent la configuration APNs de distribution.").font(.system(size:7)).foregroundStyle(Color.konsensMuted)
        }.panel()
    }
}

private struct PremiumProfileCard: View {
    @EnvironmentObject private var store: AppStore
    var body: some View { VStack(alignment:.leading,spacing:13){HStack{VStack(alignment:.leading,spacing:4){Eyebrow(text:"KONSENS PREMIUM");Text(store.subscriptionTier=="premium" ? "Intelligence financière augmentée":"Comprendre tes décisions en profondeur.").font(.title3.bold())};Spacer();Image(systemName:store.subscriptionTier=="premium" ? "checkmark.seal.fill":"crown.fill").font(.title2).foregroundStyle(store.subscriptionTier=="premium" ? Color.konsensPositive:Color.konsensViolet)};LazyVGrid(columns:[GridItem(.flexible()),GridItem(.flexible())],spacing:8){PremiumBenefit(icon:"sparkles",title:"Coach avancé",text:"Habitudes & calibration");PremiumBenefit(icon:"testtube.2",title:"Portfolio Lab",text:"Scénarios sauvegardés");PremiumBenefit(icon:"link",title:"Whale Watch",text:"10 wallets + alertes");PremiumBenefit(icon:"rectangle.slash",title:"Sans pub",text:"Parcours sans sponsor")};if store.subscriptionTier=="premium"{Label("Coach avancé, Lab, Whale Watch et expérience sans pub actifs.",systemImage:"checkmark.circle.fill").font(.caption.bold()).foregroundStyle(Color.konsensPositive)}else{VStack(alignment:.leading,spacing:8){Text("4,99 € / mois au lancement").font(.headline);Text("Bêta : active 14 jours gratuitement. Aucun paiement n’est débité pendant cette phase.").font(.caption).foregroundStyle(Color.konsensMuted);Button{Task{await store.startPremiumTrial()}}label:{Text("Activer 14 jours de Premium bêta").font(.subheadline.bold()).frame(maxWidth:.infinity).padding(12)}.buttonStyle(.plain).foregroundStyle(.white).background(Color.konsensViolet,in:RoundedRectangle(cornerRadius:14))}};Text("Premium n’augmente jamais tes Koins et ne donne aucun avantage mécanique dans les ligues.").font(.system(size:8)).foregroundStyle(Color.konsensMuted)}.padding(20).background(LinearGradient(colors:[Color.konsensViolet.opacity(0.13),Color.konsensPanel],startPoint:.topLeading,endPoint:.bottomTrailing),in:RoundedRectangle(cornerRadius:22)).overlay(RoundedRectangle(cornerRadius:22).stroke(Color.konsensViolet.opacity(0.22))) }
}
private struct PremiumBenefit:View{let icon:String;let title:String;let text:String;var body:some View{HStack(alignment:.top,spacing:7){Image(systemName:icon).font(.caption).foregroundStyle(Color.konsensViolet);VStack(alignment:.leading,spacing:2){Text(title).font(.caption.bold());Text(text).font(.system(size:7)).foregroundStyle(Color.konsensMuted)}}.frame(maxWidth:.infinity,alignment:.leading).padding(10).background(Color.white.opacity(0.035),in:RoundedRectangle(cornerRadius:12))}}
private struct ProfileStat:View{let value:String;let label:String;var body:some View{VStack(alignment:.leading,spacing:5){Text(value).font(.title3.monospacedDigit().bold());Text(label).font(.caption2).foregroundStyle(Color.konsensMuted)}.frame(maxWidth:.infinity,alignment:.leading).padding(8).background(Color.white.opacity(0.025),in:RoundedRectangle(cornerRadius:10))}}
